@ stdcall -stub D3DFree(ptr)
@ stdcall -stub D3DMalloc(ptr long)
@ stdcall -stub D3DRealloc(ptr long)
@ stdcall -stub Direct3DCreateDevice(ptr ptr ptr ptr ptr ptr)
@ stdcall -stub Direct3DCreateTexture(ptr ptr ptr ptr)
@ stdcall -stub Direct3DGetSWRastZPixFmts(ptr)
@ stdcall -stub Direct3DCreate(long long ptr)
@ stdcall -stub Direct3D_HALCleanUp(long long)
@ stdcall -stub FlushD3DDevices2(long)
@ stdcall -stub FlushD3DDevices(long)
@ stdcall -stub PaletteAssociateNotify(long long long long)
@ stdcall -stub PaletteUpdateNotify(long long long long ptr)
@ stdcall -stub SurfaceFlipNotify(long)