@ stdcall CallNtPowerInformation (long ptr long ptr long)
@ stdcall -version=0x501-0x502 CanUserWritePwrScheme ()
@ stdcall -version=0x501-0x502 DeletePwrScheme (long)
@ stdcall -stub -version=0x600+ DevicePowerClose()
@ stdcall -stub -version=0x600+ DevicePowerEnumDevices(long long long long long)
@ stdcall -stub -version=0x600+ DevicePowerOpen(long)
@ stdcall -stub -version=0x600+ DevicePowerSetDeviceState(wstr long ptr)
@ stub PowerDeterminePlatformRoleEx
@ stdcall -version=0x501-0x502 EnumPwrSchemes (ptr long)
@ stdcall -version=0x501-0x502 GetActivePwrScheme (ptr)
@ stdcall GetCurrentPowerPolicies (ptr ptr)
@ stdcall GetPwrCapabilities (ptr)
@ stdcall GetPwrDiskSpindownRange (ptr ptr)
@ stdcall IsAdminOverrideActive (ptr)
@ stdcall IsPwrHibernateAllowed ()
@ stdcall IsPwrShutdownAllowed ()
@ stdcall IsPwrSuspendAllowed ()
@ stdcall -stub -version=0x600+ PowerCanRestoreIndividualDefaultPowerScheme(ptr)
@ stdcall -stub -version=0x600+ PowerCreatePossibleSetting(ptr ptr ptr long)
@ stdcall -stub -version=0x600+ PowerCreateSetting(ptr ptr ptr)
@ stdcall -stub -version=0x600+ PowerDeleteScheme(ptr ptr)
@ stdcall -stub -version=0x600+ PowerDeterminePlatformRole()
@ stdcall -stub -version=0x600+ PowerDuplicateScheme(ptr ptr ptr)
@ stdcall -stub -version=0x600+ PowerEnumerate(ptr ptr ptr ptr long str long)
@ stdcall -stub -version=0x600+ PowerImportPowerScheme(ptr wstr ptr)
@ stdcall -stub -version=0x601+ PowerIsSettingRangeDefined(ptr ptr)
@ stdcall PowerGetActiveScheme (ptr ptr)
@ stdcall -stub -version=0x600+ PowerReadACValue(ptr ptr ptr ptr long long long)
@ stdcall PowerReadDCValue (ptr ptr ptr ptr ptr ptr ptr)
@ stdcall -stub -version=0x600+ PowerReadDescription(ptr ptr ptr ptr str long)
@ stdcall -stub -version=0x600+ PowerReadFriendlyName(ptr ptr ptr ptr str long)
@ stdcall -stub -version=0x600+ PowerReadIconResourceSpecifier(ptr ptr ptr ptr str long)
@ stdcall -stub -version=0x600+ PowerReadPossibleDescription(ptr ptr ptr long str long)
@ stdcall -stub -version=0x600+ PowerReadPossibleFriendlyName(ptr ptr ptr long str long)
@ stdcall -stub -version=0x600+ PowerReadPossibleValue(ptr ptr ptr long long str long)
@ stdcall -stub -version=0x600+ PowerReadSettingAttributes(ptr ptr)
@ stub -version=0x600+ PowerWriteDCValue
@ stub -version=0x600+ PowerWriteACValue
@ stdcall -stub -version=0x600+ PowerReadValueIncrement(ptr ptr ptr long)
@ stdcall -stub -version=0x600+ PowerReadValueMax(ptr ptr ptr long)
@ stdcall -stub -version=0x600+ PowerReadValueMin(ptr ptr ptr long)
@ stdcall -stub -version=0x600+ PowerReadValueUnitsSpecifier(ptr ptr ptr str long)
@ stdcall -stub -version=0x600+ PowerRemovePowerSetting(ptr ptr)
@ stdcall -stub -version=0x600+ PowerReplaceDefaultPowerSchemes()
@ stdcall -stub -version=0x600+ PowerRestoreDefaultPowerSchemes()
@ stdcall -stub -version=0x600+ PowerRestoreIndividualDefaultPowerScheme(ptr)
@ stdcall -stub -version=0x600+ PowerSetActiveScheme(ptr ptr)
@ stdcall -stub -version=0x600+ PowerSettingAccessCheck(ptr ptr)
@ stdcall -stub -version=0x601+ PowerSettingAccessCheckEx(ptr ptr ptr)
@ stdcall -stub -version=0x601+ PowerSettingRegisterNotification(ptr long ptr ptr)
@ stdcall -stub -version=0x601+ PowerSettingUnregisterNotification(ptr)
@ stdcall -stub -version=0x600+ PowerWriteDescription(ptr ptr ptr ptr str long)
@ stdcall -stub -version=0x600+ PowerWriteFriendlyName(ptr ptr ptr ptr str long)
@ stdcall -stub -version=0x600+ PowerWriteIconResourceSpecifier(ptr ptr ptr ptr str long)
@ stdcall -stub -version=0x600+ PowerWritePossibleDescription(ptr ptr ptr long str long)
@ stdcall -stub -version=0x600+ PowerWritePossibleFriendlyName(ptr ptr ptr long str long)
@ stdcall -stub -version=0x600+ PowerWritePossibleValue(ptr ptr ptr long long str long)
@ stdcall -stub -version=0x600+ PowerWriteSettingAttributes(ptr ptr long)
@ stdcall -stub -version=0x600+ PowerWriteValueIncrement(ptr ptr ptr long)
@ stdcall -stub -version=0x600+ PowerWriteValueMax(ptr ptr ptr long)
@ stdcall -stub -version=0x600+ PowerWriteValueMin(ptr ptr ptr long)
@ stdcall -stub -version=0x600+ PowerWriteValueUnitsSpecifier(ptr ptr ptr str long)
@ stdcall ReadGlobalPwrPolicy (ptr)
@ stdcall ReadProcessorPwrScheme (long ptr)
@ stdcall ReadPwrScheme (long ptr)
@ stdcall -version=0x501-0x502 SetActivePwrScheme (long ptr ptr)
@ stdcall SetSuspendState (long long long)
@ stdcall WriteGlobalPwrPolicy (ptr)
@ stdcall WriteProcessorPwrScheme (long ptr)
@ stdcall -version=0x501-0x502 WritePwrScheme (ptr str str ptr)
@ stdcall ValidatePowerPolicies (ptr ptr)