
# This file is autogenerated by update.py

@ stdcall __isascii() msvcrt.__isascii
@ stdcall __iscsym() msvcrt.__iscsym
@ stdcall __iscsymf() msvcrt.__iscsymf
@ stub __iswcsym
@ stub __iswcsymf
@ stub __strncnt
@ stub __wcsncnt
@ cdecl -version=0x600+ _isalnum_l(long ptr) msvcrt._isalnum_l
@ cdecl -version=0x600+ _isalpha_l(long ptr) msvcrt._isalpha_l
@ stub _isblank_l
@ cdecl -version=0x600+ _iscntrl_l(long ptr) msvcrt._iscntrl_l
@ stdcall _isctype() msvcrt._isctype
@ cdecl -version=0x600+ _iscntrl_l(long ptr) msvcrt._iscntrl_l
@ cdecl -version=0x600+ _isctype_l(long long ptr) msvcrt._isctype_l
@ cdecl -version=0x600+ _isdigit_l(long ptr) msvcrt._isdigit_l
@ cdecl -version=0x600+ _isgraph_l(long ptr) msvcrt._isgraph_l
@ cdecl -version=0x600+ _isleadbyte_l(long ptr) msvcrt._isleadbyte_l
@ cdecl -version=0x600+ _islower_l(long ptr) msvcrt._islower_l
@ cdecl -version=0x600+ _isprint_l(long ptr) msvcrt._isprint_l
@ cdecl -version=0x600+ _isspace_l(long ptr) msvcrt._isspace_l
@ cdecl -version=0x600+ _isupper_l(long ptr) msvcrt._isupper_l
@ cdecl -version=0x600+ _iswalnum_l(long ptr) msvcrt._iswalnum_l
@ cdecl -version=0x600+ _iswalpha_l(long ptr) msvcrt._iswalpha_l
@ stub _iswblank_l
@ cdecl -version=0x600+ _iswcntrl_l(long ptr) msvcrt._iswcntrl_l
@ stub _iswcsym_l
@ stub _iswcsymf_l
@ cdecl -version=0x600+ _iswctype_l(long ptr) msvcrt._iswctype_l
@ cdecl -version=0x600+ _iswdigit_l(long ptr) msvcrt._iswdigit_l
@ cdecl -version=0x600+ _iswgraph_l(long ptr) msvcrt._iswgraph_l
@ cdecl -version=0x600+ _iswlower_l(long ptr) msvcrt._iswlower_l
@ cdecl -version=0x600+ _iswprint_l(long ptr) msvcrt._iswprint_l
@ cdecl -version=0x600+ _iswpunct_l(long ptr) msvcrt._iswpunct_l
@ cdecl -version=0x600+ _iswspace_l(long ptr) msvcrt._iswspace_l
@ cdecl -version=0x600+ _iswupper_l(long ptr) msvcrt._iswupper_l
@ cdecl -version=0x600+ _iswxdigit_l(long ptr) msvcrt._iswxdigit_l
@ cdecl -version=0x600+ _isxdigit_l(long ptr) msvcrt._isxdigit_l
@ stdcall _memccpy() msvcrt._memccpy
@ stdcall _memicmp() msvcrt._memicmp
@ cdecl -version=0x600+ _memicmp_l(ptr ptr long ptr) msvcrt._memicmp_l
@ cdecl -version=0x600+ _strcoll_l(str str ptr) msvcrt._strcoll_l
@ stdcall _strdup() msvcrt._strdup
@ stdcall _stricmp() msvcrt._stricmp
@ cdecl -version=0x600+ _stricmp_l(str str ptr) msvcrt._stricmp_l
@ stdcall _stricoll() msvcrt._stricoll
@ cdecl -version=0x600+ _stricoll_l(str str ptr) msvcrt._stricoll_l
@ stdcall _strlwr() msvcrt._strlwr
@ stub _strlwr_l
@ cdecl -version=0x600+ _strlwr_s(str long) msvcrt._strlwr_s
@ cdecl -version=0x600+ _strlwr_s_l(str long ptr) msvcrt._strlwr_s_l
@ stdcall _strncoll() msvcrt._strncoll
@ cdecl -version=0x600+ _strncoll_l(str str long ptr) msvcrt._strncoll_l
@ stdcall _strnicmp() msvcrt._strnicmp
@ cdecl -version=0x600+ _strnicmp_l(str str long ptr) msvcrt._strnicmp_l
@ stdcall _strnicoll() msvcrt._strnicoll
@ cdecl -version=0x600+ _strnicoll_l(str str long ptr) msvcrt._strnicoll_l
@ stdcall _strnset() msvcrt._strnset
@ cdecl -version=0x600+ _strnset_s(str long long long) msvcrt._strnset_s
@ stdcall _strrev() msvcrt._strrev
@ stdcall _strset() msvcrt._strset
@ cdecl -version=0x600+ _strset_s(str long long) msvcrt._strset_s
@ stdcall _strupr() msvcrt._strupr
@ cdecl -version=0x600+ _strupr_l(str ptr) msvcrt._strupr_l
@ cdecl -version=0x600+ _strupr_s(str long) msvcrt._strupr_s
@ cdecl -version=0x600+ _strupr_s_l(str long ptr) msvcrt._strupr_s_l
@ cdecl -version=0x600+ _strxfrm_l(ptr str long ptr) msvcrt._strxfrm_l
@ stdcall _tolower() msvcrt._tolower
@ cdecl -version=0x600+ _tolower_l(long ptr) msvcrt._tolower_l
@ stdcall _toupper() msvcrt._toupper
@ cdecl -version=0x600+ _toupper_l(long ptr) msvcrt._toupper_l
@ cdecl -version=0x600+ _towlower_l(long ptr) msvcrt._towlower_l
@ cdecl -version=0x600+ _towupper_l(long ptr) msvcrt._towupper_l
@ cdecl -version=0x600+ _wcscoll_l(str str ptr) msvcrt._wcscoll_l
@ stdcall _wcsdup() msvcrt._wcsdup
@ stdcall _wcsicmp() msvcrt._wcsicmp
@ cdecl -version=0x600+ _wcsicmp_l(wstr wstr ptr) msvcrt._wcsicmp_l
@ stdcall _wcsicoll() msvcrt._wcsicoll
@ cdecl -version=0x600+ _wcsicoll_l(wstr wstr ptr) msvcrt._wcsicoll_l
@ stdcall _wcslwr() msvcrt._wcslwr
@ cdecl -version=0x600+ _wcslwr_l(wstr ptr) msvcrt._wcslwr_l
@ cdecl -version=0x600+ _wcslwr_s(wstr long) msvcrt._wcslwr_s
@ cdecl -version=0x600+ _wcslwr_s_l(wstr long ptr) msvcrt._wcslwr_s_l
@ stdcall _wcsncoll() msvcrt._wcsncoll
@ cdecl -version=0x600+ _wcsncoll_l(wstr wstr long ptr) msvcrt._wcsncoll_l
@ stdcall _wcsnicmp() msvcrt._wcsnicmp
@ cdecl -version=0x600+ _wcsnicmp_l(wstr wstr long ptr) msvcrt._wcsnicmp_l
@ stdcall _wcsnicoll() msvcrt._wcsnicoll
@ cdecl -version=0x600+ _wcsnicoll_l(wstr str long ptr) msvcrt._wcsnicoll_l
@ stdcall _wcsnset() msvcrt._wcsnset
@ cdecl -version=0x600+ _wcsnset_s(wstr long long long) msvcrt._wcsnset_s
@ stdcall _wcsrev() msvcrt._wcsrev
@ stdcall _wcsset() msvcrt._wcsset
@ cdecl -version=0x600+ _wcsset_s(ptr long long) msvcrt._wcsset_s
@ stdcall _wcsupr() msvcrt._wcsupr
@ cdecl -version=0x600+ _wcsupr_l(wstr ptr) msvcrt._wcsupr_l
@ cdecl -version=0x600+ _wcsupr_s(wstr long) msvcrt._wcsupr_s
@ cdecl -version=0x600+ _wcsupr_s_l(ptr long ptr) msvcrt._wcsupr_s_l
@ cdecl -version=0x600+ _wcsxfrm_l(ptr wstr long ptr) msvcrt._wcsxfrm_l
@ stub _wctype
@ stdcall is_wctype() msvcrt.is_wctype
@ stdcall isalnum() msvcrt.isalnum
@ stdcall isalpha() msvcrt.isalpha
@ stub isblank
@ stdcall iscntrl() msvcrt.iscntrl
@ stdcall isdigit() msvcrt.isdigit
@ stdcall isgraph() msvcrt.isgraph
@ stdcall isleadbyte() msvcrt.isleadbyte
@ stdcall islower() msvcrt.islower
@ stdcall isprint() msvcrt.isprint
@ stdcall ispunct() msvcrt.ispunct
@ stdcall isspace() msvcrt.isspace
@ stdcall isupper() msvcrt.isupper
@ stdcall iswalnum() msvcrt.iswalnum
@ stdcall iswalpha() msvcrt.iswalpha
@ stdcall iswascii() msvcrt.iswascii
@ stub iswblank
@ stdcall iswcntrl() msvcrt.iswcntrl
@ stdcall iswctype() msvcrt.iswctype
@ stdcall iswdigit() msvcrt.iswdigit
@ stdcall iswgraph() msvcrt.iswgraph
@ stdcall iswlower() msvcrt.iswlower
@ stdcall iswprint() msvcrt.iswprint
@ stdcall iswpunct() msvcrt.iswpunct
@ stdcall iswspace() msvcrt.iswspace
@ stdcall iswupper() msvcrt.iswupper
@ stdcall iswxdigit() msvcrt.iswxdigit
@ stdcall isxdigit() msvcrt.isxdigit
@ stdcall mblen() msvcrt.mblen
@ cdecl -version=0x600+ mbrlen(str long ptr) msvcrt.mbrlen
@ cdecl -version=0x600+ memcpy_s(ptr long ptr long) msvcrt.memcpy_s
@ cdecl -version=0x600+ memmove_s(ptr long ptr long) msvcrt.memmove_s
@ stdcall memset() msvcrt.memset
@ stdcall strcat() msvcrt.strcat
@ cdecl -version=0x600+ strcat_s(ptr long str) msvcrt.strcat_s
@ stdcall strcmp() msvcrt.strcmp
@ stdcall strcoll() msvcrt.strcoll
@ stdcall strcpy() msvcrt.strcpy
@ cdecl -version=0x600+ strcpy_s(ptr long str) msvcrt.strcpy_s
@ stdcall strcspn() msvcrt.strcspn
@ stdcall strlen() msvcrt.strlen
@ stdcall strncat() msvcrt.strncat
@ cdecl -version=0x600+ strncat_s(str long str long) msvcrt.strncat_s
@ stdcall strncmp() msvcrt.strncmp
@ stdcall strncpy() msvcrt.strncpy
@ cdecl -version=0x600+ strncpy_s(ptr long str long) msvcrt.strncpy_s
@ stub _mbstrnlen
@ stdcall strpbrk() msvcrt.strpbrk
@ stdcall strspn() msvcrt.strspn
@ stdcall strtok() msvcrt.strtok
@ cdecl -version=0x600+ strtok_s(str str ptr) msvcrt.strtok_s
@ stdcall strxfrm() msvcrt.strxfrm
@ stdcall tolower() msvcrt.tolower
@ stdcall toupper() msvcrt.toupper
@ stub towctrans
@ stdcall towlower() msvcrt.towlower
@ stdcall towupper() msvcrt.towupper
@ stdcall wcscat() msvcrt.wcscat
@ cdecl -version=0x600+ wcscat_s(wstr long wstr) msvcrt.wcscat_s
@ stdcall wcscmp() msvcrt.wcscmp
@ stdcall wcscoll() msvcrt.wcscoll
@ stdcall wcscpy() msvcrt.wcscpy
@ cdecl -version=0x600+ wcscpy_s(wstr long wstr) msvcrt.wcscpy_s
@ stdcall wcscspn() msvcrt.wcscspn
@ stdcall wcslen() msvcrt.wcslen
@ stdcall wcsncat() msvcrt.wcsncat
@ cdecl -version=0x600+ wcsncat_s(wstr long wstr long) msvcrt.wcsncat_s
@ stdcall wcsncmp() msvcrt.wcsncmp
@ stdcall wcsncpy() msvcrt.wcsncpy
@ cdecl -version=0x600+ wcsncpy_s(ptr long wstr long) msvcrt.wcsncpy_s
@ cdecl -version=0x600+ wcsnlen(wstr long) msvcrt.wcsnlen
@ stdcall wcspbrk() msvcrt.wcspbrk
@ stdcall wcsspn() msvcrt.wcsspn
@ stdcall wcstok() msvcrt.wcstok
@ cdecl -version=0x600+ wcstok_s(wstr wstr ptr) msvcrt.wcstok_s
@ stdcall wcsxfrm() msvcrt.wcsxfrm
@ cdecl -arch=i386 __p__pwctype() msvcrt.wctype
@ stub wmemcpy_s
@ stub wmemmove_s
