
# This file is autogenerated by update.py

@ cdecl -version=0x600+ _aligned_msize(ptr long long) msvcrt._aligned_msize
@ stdcall _aligned_malloc() msvcrt._aligned_malloc
@ stub _aligned_msize
@ stdcall _aligned_offset_malloc() msvcrt._aligned_offset_malloc
@ stdcall _aligned_offset_realloc() msvcrt._aligned_offset_realloc
@ stub _aligned_offset_recalloc
@ stdcall _aligned_realloc() msvcrt._aligned_realloc
@ stub _aligned_recalloc
@ stdcall _callnewh() msvcrt._callnewh
@ cdecl -version=0x600+ _calloc_base(long long) msvcrt._calloc_base
@ stdcall _expand() msvcrt._expand
@ cdecl -version=0x600+ _free_base(ptr) msvcrt._free_base
@ cdecl -version=0x600+ _get_heap_handle() msvcrt._get_heap_handle
@ stdcall _heapchk() msvcrt._heapchk
@ stdcall _heapmin() msvcrt._heapmin
@ stdcall _heapwalk() msvcrt._heapwalk
@ cdecl -version=0x600+ _malloc_base(long) msvcrt._malloc_base
@ stdcall _msize() msvcrt._msize
@ cdecl -version=0x600+ _query_new_handler() msvcrt._query_new_handler
@ cdecl -version=0x600+ _query_new_mode() msvcrt._query_new_mode
@ cdecl -version=0x600+ _realloc_base(ptr long) msvcrt._realloc_base
@ cdecl -version=0x600+ _recalloc(ptr long long) msvcrt._recalloc
@ cdecl -version=0x600+ _set_new_mode(long) msvcrt._set_new_mode
@ stdcall calloc() msvcrt.calloc
@ stdcall free() msvcrt.free
@ stdcall malloc() msvcrt.malloc
@ stdcall realloc() msvcrt.realloc
