
# This file is autogenerated by update.py

@ stdcall -stub -version=0x602+ GetProcessReference(ptr)
@ stdcall SHCreateThread() shlwapi.SHCreateThread
@ stdcall SHCreateThreadRef() shlwapi.SHCreateThreadRef
@ stdcall -stub -version=0x600+ SHCreateThreadWithHandle(long ptr long ptr ptr)
@ stdcall SHGetThreadRef() shlwapi.SHGetThreadRef
@ stdcall SHReleaseThreadRef() shlwapi.SHReleaseThreadRef
@ stdcall SHSetThreadRef() shlwapi.SHSetThreadRef
@ stdcall -stub -version=0x602+ SetProcessReference(ptr)
