
# This file is autogenerated by update.py

@ stdcall BaseCheckAppcompatCache() kernel32.BaseCheckAppcompatCache
@ stdcall -version=0x603+ BaseCheckAppcompatCacheEx() kernel32.BaseCheckAppcompatCacheEx
@ stdcall BaseCleanupAppcompatCacheSupport() kernel32.BaseCleanupAppcompatCacheSupport
@ stdcall BaseDumpAppcompatCache() kernel32.BaseDumpAppcompatCache
@ stdcall BaseFlushAppcompatCache() kernel32.BaseFlushAppcompatCache
@ stub BaseFreeAppCompatDataForProcess
@ stdcall BaseInitAppcompatCacheSupport() kernel32.BaseInitAppcompatCacheSupport
@ stdcall BaseIsAppcompatInfrastructureDisabled() kernel32.BaseIsAppcompatInfrastructureDisabled
@ stub BaseReadAppCompatDataForProcess
@ stdcall BaseUpdateAppcompatCache() kernel32.BaseUpdateAppcompatCache
