
# This file is autogenerated by update.py

@ stdcall -version=0x602+ PathAllocCanonicalize() KernelBase.PathAllocCanonicalize
@ stdcall -version=0x602+ PathAllocCombine() KernelBase.PathAllocCombine
@ stdcall -version=0x602+ PathCchAddBackslash() KernelBase.PathCchAddBackslash
@ stdcall -version=0x602+ PathCchAddBackslashEx() KernelBase.PathCchAddBackslashEx
@ stdcall -version=0x602+ PathCchAddExtension() KernelBase.PathCchAddExtension
@ stdcall -version=0x602+ PathCchAppend() KernelBase.PathCchAppend
@ stdcall -version=0x602+ PathCchAppendEx() KernelBase.PathCchAppendEx
@ stdcall -version=0x602+ PathCchCanonicalize() KernelBase.PathCchCanonicalize
@ stdcall -version=0x602+ PathCchCanonicalizeEx() Kernelbase.PathCchCanonicalizeEx
@ stdcall -version=0x602+ PathCchCombine() KernelBase.PathCchCombine
@ stdcall -version=0x602+ PathCchCombineEx() KernelBase.PathCchCombineEx
@ stdcall -version=0x602+ PathCchFindExtension() KernelBase.PathCchFindExtension
@ stdcall -version=0x602+ PathCchIsRoot() KernelBase.PathCchIsRoot
@ stdcall -version=0x602+ PathCchRemoveBackslash() KernelBase.PathCchRemoveBackslash
@ stdcall -version=0x602+ PathCchRemoveBackslashEx() KernelBase.PathCchRemoveBackslashEx
@ stdcall -version=0x602+ PathCchRemoveExtension() KernelBase.PathCchRemoveExtension
@ stdcall -version=0x602+ PathCchRemoveFileSpec() KernelBase.PathCchRemoveFileSpec
@ stdcall -version=0x602+ PathCchRenameExtension() KernelBase.PathCchRenameExtension
@ stdcall -version=0x602+ PathCchSkipRoot() KernelBase.PathCchSkipRoot
@ stdcall -version=0x602+ PathCchStripPrefix() KernelBase.PathCchStripPrefix
@ stdcall -version=0x602+ PathCchStripToRoot() KernelBase.PathCchStripToRoot
@ stdcall -version=0x602+ PathIsUNCEx() KernelBase.PathIsUNCEx
