
# This file is autogenerated by update.py

@ stdcall _aligned_free() msvcrt._aligned_free
@ stdcall _aligned_malloc() msvcrt._aligned_malloc
@ stdcall -version=0x600+ _aligned_msize() msvcrt._aligned_msize
@ stdcall _aligned_offset_malloc() msvcrt._aligned_offset_malloc
@ stdcall _aligned_offset_realloc() msvcrt._aligned_offset_realloc
@ stub _aligned_offset_recalloc
@ stdcall _aligned_realloc() msvcrt._aligned_realloc
@ stub _aligned_recalloc
@ stdcall _callnewh() msvcrt._callnewh
@ stdcall -version=0x600+ _calloc_base() msvcrt._calloc_base
@ stdcall _expand() msvcrt._expand
@ stdcall -version=0x600+ _free_base() msvcrt._free_base
@ stdcall -version=0x600+ _get_heap_handle() msvcrt._get_heap_handle
@ stdcall _heapchk() msvcrt._heapchk
@ stdcall _heapmin() msvcrt._heapmin
@ stdcall _heapwalk() msvcrt._heapwalk
@ stdcall -version=0x600+ _malloc_base() msvcrt._malloc_base
@ stdcall _msize() msvcrt._msize
@ stdcall -version=0x600+ _query_new_handler() msvcrt._query_new_handler
@ stdcall -version=0x600+ _query_new_mode() msvcrt._query_new_mode
@ stdcall -version=0x600+ _realloc_base() msvcrt._realloc_base
@ stdcall -version=0x600+ _recalloc() msvcrt._recalloc
@ stdcall -version=0x600+ _set_new_mode() msvcrt._set_new_mode
@ stdcall calloc() msvcrt.calloc
@ stdcall free() msvcrt.free
@ stdcall malloc() msvcrt.malloc
@ stdcall realloc() msvcrt.realloc
