
# This file is autogenerated by update.py

@ stdcall -version=0x600+ -arch=win32 CommandLineToArgvW() shell32.CommandLineToArgvW
@ stdcall -version=0x600+ -arch=win32 GetCurrentProcessExplicitAppUserModelID() shell32.GetCurrentProcessExplicitAppUserModelID
@ stdcall -version=0x600+ -arch=win32 SetCurrentProcessExplicitAppUserModelID() shell32.SetCurrentProcessExplicitAppUserModelID
