
# This file is autogenerated by update.py

@ stdcall __isascii() msvcrt.__isascii
@ stdcall __iscsym() msvcrt.__iscsym
@ stdcall __iscsymf() msvcrt.__iscsymf
@ stub __iswcsym
@ stub __iswcsymf
@ stub __strncnt
@ stub __wcsncnt
@ stub _isalnum_l
@ stub _isalpha_l
@ stub _isblank_l
@ stub _iscntrl_l
@ stdcall _isctype() msvcrt._isctype
@ stub _isctype_l
@ stub _isdigit_l
@ stub _isgraph_l
@ stub _isleadbyte_l
@ stub _islower_l
@ stub _isprint_l
@ stub _ispunct_l
@ stub _isspace_l
@ stub _isupper_l
@ stub _iswalnum_l
@ stub _iswalpha_l
@ stub _iswblank_l
@ stub _iswcntrl_l
@ stub _iswcsym_l
@ stub _iswcsymf_l
@ stub _iswctype_l
@ stub _iswdigit_l
@ stub _iswgraph_l
@ stub _iswlower_l
@ stub _iswprint_l
@ stub _iswpunct_l
@ stub _iswspace_l
@ stub _iswupper_l
@ stub _iswxdigit_l
@ stub _isxdigit_l
@ stdcall _memccpy() msvcrt._memccpy
@ stdcall _memicmp() msvcrt._memicmp
@ stub _memicmp_l
@ stub _strcoll_l
@ stdcall _strdup() msvcrt._strdup
@ stdcall _stricmp() msvcrt._stricmp
@ stub _stricmp_l
@ stdcall _stricoll() msvcrt._stricoll
@ stub _stricoll_l
@ stdcall _strlwr() msvcrt._strlwr
@ stub _strlwr_l
@ stub _strlwr_s
@ stub _strlwr_s_l
@ stdcall _strncoll() msvcrt._strncoll
@ stub _strncoll_l
@ stdcall _strnicmp() msvcrt._strnicmp
@ stub _strnicmp_l
@ stdcall _strnicoll() msvcrt._strnicoll
@ stub _strnicoll_l
@ stdcall _strnset() msvcrt._strnset
@ stub _strnset_s
@ stdcall _strrev() msvcrt._strrev
@ stdcall _strset() msvcrt._strset
@ stub _strset_s
@ stdcall _strupr() msvcrt._strupr
@ stub _strupr_l
@ stub _strupr_s
@ stub _strupr_s_l
@ stub _strxfrm_l
@ stdcall _tolower() msvcrt._tolower
@ stub _tolower_l
@ stdcall _toupper() msvcrt._toupper
@ stdcall _toupper_l() msvcrt._towupper_l
@ stdcall _towlower_l() msvcrt._tolower_l
@ stdcall _towupper_l() msvcrt._towupper_l
@ stdcall _wcscoll_l() msvcrt._wcscoll_l
@ stdcall _wcsdup() msvcrt._wcsdup
@ stdcall _wcsicmp() msvcrt._wcsicmp
@ stdcall _wcsicmp_l() msvcrt._wcsicmp_l
@ stdcall _wcsicoll() msvcrt._wcsicoll
@ stdcall _wcsicoll_l() msvcrt._wcsicoll_l
@ stdcall _wcslwr() msvcrt._wcslwr
@ stdcall -version=0x600+ _wcslwr_l() msvcrt._wcslwr_l
@ stdcall -version=0x600+ _wcslwr_s() msvcrt._wcslwr_s
@ stdcall -version=0x600+ _wcslwr_s_l() msvcrt._wcslwr_s_l
@ stdcall _wcsncoll() msvcrt._wcsncoll
@ stdcall _wcsncoll_l() msvcrt._wcsncoll_l
@ stdcall _wcsnicmp() msvcrt._wcsnicmp
@ stdcall _wcsnicmp_l() msvcrt._wcsnicmp_l
@ stdcall _wcsnicoll() msvcrt._wcsnicoll
@ stdcall _wcsnicoll_l() msvcrt._wcsnicoll_l
@ stdcall _wcsnset() msvcrt._wcsnset
@ stdcall _wcsnset_s() msvcrt._wcsnset_s
@ stdcall _wcsrev() msvcrt._wcsrev
@ stdcall _wcsset() msvcrt._wcsset
@ stdcall _wcsset_s() msvcrt._wcsset_s
@ stdcall _wcsupr() msvcrt._wcsupr
@ stdcall _wcsupr_l() msvcrt._wcsupr_l
@ stdcall _wcsupr_s() msvcrt._wcsupr_s
@ stdcall _wcsupr_s_l() msvcrt._wcsupr_s_l
@ stdcall _wcsxfrm_l() msvcrt._wcsxfrm_l
@ stub _wctype
@ stdcall is_wctype() msvcrt.is_wctype
@ stdcall isalnum() msvcrt.isalnum
@ stdcall isalpha() msvcrt.isalpha
@ stub isblank
@ stdcall iscntrl() msvcrt.iscntrl
@ stdcall isdigit() msvcrt.isdigit
@ stdcall isgraph() msvcrt.isgraph
@ stdcall isleadbyte() msvcrt.isleadbyte
@ stdcall islower() msvcrt.islower
@ stdcall isprint() msvcrt.isprint
@ stdcall ispunct() msvcrt.ispunct
@ stdcall isspace() msvcrt.isspace
@ stdcall isupper() msvcrt.isupper
@ stdcall iswalnum() msvcrt.iswalnum
@ stdcall iswalpha() msvcrt.iswalpha
@ stdcall iswascii() msvcrt.iswascii
@ stub iswblank
@ stdcall iswcntrl() msvcrt.iswcntrl
@ stdcall iswctype() msvcrt.iswctype
@ stdcall iswdigit() msvcrt.iswdigit
@ stdcall iswgraph() msvcrt.iswgraph
@ stdcall iswlower() msvcrt.iswlower
@ stdcall iswprint() msvcrt.iswprint
@ stdcall iswpunct() msvcrt.iswpunct
@ stdcall iswspace() msvcrt.iswspace
@ stdcall iswupper() msvcrt.iswupper
@ stdcall iswxdigit() msvcrt.iswxdigit
@ stdcall isxdigit() msvcrt.isxdigit
@ stdcall mblen() msvcrt.mblen
@ stdcall mbrlen() msvcrt.mbrlen
@ stdcall memcpy_s() msvcrt.memcpy_s
@ stdcall memmove_s() msvcrt.memmove_s
@ stdcall memset() msvcrt.memset
@ stdcall strcat() msvcrt.strcat
@ stdcall strcat_s() msvcrt.strcat_s
@ stdcall strcmp() msvcrt.strcmp
@ stdcall strcoll() msvcrt.strcoll
@ stdcall strcpy() msvcrt.strcpy
@ stdcall strcpy_s() msvcrt.strcpy_s
@ stdcall strcspn() msvcrt.strcspn
@ stdcall strlen() msvcrt.strlen
@ stdcall strncat() msvcrt.strncat
@ stdcall strncat_s() msvcrt.strncat_s
@ stdcall strncmp() msvcrt.strncmp
@ stdcall strncpy() msvcrt.strncpy
@ stdcall strncpy_s() msvcrt.strncpy_s
@ stdcall strnlen() msvcrt.strnlen
@ stdcall strpbrk() msvcrt.strpbrk
@ stdcall strspn() msvcrt.strspn
@ stdcall strtok() msvcrt.strtok
@ stdcall strtok_s() msvcrt.strtok_s
@ stdcall strxfrm() msvcrt.strxfrm
@ stdcall tolower() msvcrt.tolower
@ stdcall toupper() msvcrt.toupper
@ stub towctrans
@ stdcall towlower() msvcrt.towlower
@ stdcall towupper() msvcrt.towupper
@ stdcall wcscat() msvcrt.wcscat
@ stdcall -version=0x600+ wcscat_s() msvcrt.wcscat_s
@ stdcall wcscmp() msvcrt.wcscmp
@ stdcall wcscoll() msvcrt.wcscoll
@ stdcall wcscpy() msvcrt.wcscpy
@ stdcall -version=0x600+ wcscpy_s() msvcrt.wcscpy_s
@ stdcall wcscspn() msvcrt.wcscspn
@ stdcall wcslen() msvcrt.wcslen
@ stdcall wcsncat() msvcrt.wcsncat
@ stdcall wcsncat_s() msvcrt.wcsncat_s
@ stdcall wcsncmp() msvcrt.wcsncmp
@ stdcall wcsncpy() msvcrt.wcsncpy
@ stdcall wcsncpy_s() msvcrt.wcsncpy_s
@ stdcall wcsnlen() msvcrt.wcsnlen
@ stdcall wcspbrk() msvcrt.wcspbrk
@ stdcall wcsspn() msvcrt.wcsspn
@ stdcall wcstok() msvcrt.wcstok
@ stdcall -version=0x600+ wcstok_s() msvcrt.wcstok_s
@ stdcall wcsxfrm() msvcrt.wcsxfrm
@ stub wctype
@ stub wmemcpy_s
@ stub wmemmove_s
