
# This file is autogenerated by update.py

@ stdcall -stub -version=0xA00+ AppContainerDeriveSidFromMoniker(ptr long)
@ stdcall -stub -version=0xA00+ AppContainerFreeMemory(ptr ptr ptr) ; fuck
@ stdcall -stub -version=0xA00+ AppContainerLookupDisplayNameMrtReference(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppContainerLookupMoniker(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppContainerRegisterSid(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppContainerUnregisterSid(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXFreeMemory(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXGetApplicationData(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXGetDevelopmentMode(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXGetOSMaxVersionTested(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXGetOSMinVersion(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXGetPackageCapabilities(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXGetPackageSid(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXGetPackageState(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXLookupDisplayName(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXLookupMoniker(ptr ptr ptr ptr) ; fuckl
@ stdcall -stub -version=0xA00+ AppXSetPackageState(ptr ptr ptr ptr) ; fuckl
