
# This file is autogenerated by update.py

@ stdcall -version=0x600+ EventActivityIdControl() advapi32.EventActivityIdControl 
@ stdcall -version=0x600+ EventEnabled() advapi32.EventEnabled 
@ stdcall -version=0x600+ EventProviderEnabled() advapi32.EventProviderEnabled 
@ stdcall -version=0x600+ EventRegister() advapi32.EventRegister 
@ stdcall -version=0x600+ EventSetInformation() advapi32.EventSetInformation 
@ stdcall -version=0x600+ EventUnregister() advapi32.EventUnregister 
@ stdcall -version=0x600+ EventWrite() advapi32.EventWrite 
@ stdcall -stub -version=0x600+ EventWriteEx(long ptr long long long long long ptr)
@ stdcall -version=0x600+ EventWriteString() advapi32.EventWriteString 
@ stdcall -version=0x600+ EventWriteTransfer() advapi32.EventWriteTransfer 
