
# This file is autogenerated by update.py

@ stdcall _Getdays() msvcrt._Getdays
@ stdcall _Getmonths() msvcrt._Getmonths
@ stdcall _Gettnames() msvcrt._Gettnames
@ stdcall _Strftime() msvcrt._Strftime
@ stdcall -stub _W_Getdays()
@ stdcall -stub _W_Getmonths()
@ stdcall -stub _W_Gettnames()
@ stdcall  _Wcsftime() msvcrt.wcsftime
;@ stub __daylight
;@ stub __dstbias
;@ stub __timezone
;@ stub __tzname
;@ stub _ctime32
;@ stub _ctime32_s
@ stdcall _ctime64() msvcrt._ctime64
@ stdcall _ctime64_s() msvcrt._ctime64_s
@ stdcall _difftime32() msvcrt._difftime32
@ stdcall _difftime64() msvcrt._difftime64
;@ stub _ftime32
;@ stub _ftime32_s
@ stdcall _ftime64() msvcrt._ftime64
@ stdcall _ftime64_s() msvcrt._ftime64_s
;@ stub _futime32
@ stdcall _futime64() msvcrt._futime64
;@ stub _get_daylight
;@ stub _get_dstbias
@ stdcall -stub _get_timezone(ptr)
;@ stub _get_tzname
@ stdcall _getsystime() msvcrt._getsystime
@ stdcall _gmtime32()
@ stdcall _gmtime32_s()
@ stdcall _gmtime64() msvcrt._gmtime64
@ stdcall -version=0x600+ _gmtime64_s() msvcrt._gmtime64_s
@ stdcall _localtime32()
@ stdcall _localtime32_s()
@ stdcall _localtime64() msvcrt._localtime64
@ stdcall _localtime64_s()
@ stdcall _mkgmtime32()
@ stdcall _mkgmtime64() msvcrt._mkgmtime64
@ stdcall _mktime32()
@ stdcall _mktime64() msvcrt._mktime64
@ stdcall _setsystime() msvcrt._setsystime
@ stdcall _strdate() msvcrt._strdate
@ stdcall _strdate_s()
@ stdcall -stub _strftime_l()
@ stdcall _strtime() msvcrt._strtime
@ stdcall _strtime_s()
@ stdcall _time32()
@ stdcall _time64() msvcrt._time64
@ stdcall -stub _timespec32_get()
@ stdcall -stub _timespec64_get()
@ stdcall _tzset() msvcrt._tzset
;@ stub _utime32
@ stdcall _utime64() msvcrt._utime64
@ stdcall _wasctime() msvcrt._wasctime
;@ stub _wasctime_s
;@ stub _wcsftime_l
;@ stub _wctime32
;@ stub _wctime32_s
@ stdcall _wctime64() msvcrt._wctime64
;@ stub _wctime64_s
@ stdcall _wstrdate() msvcrt._wstrdate
;@ stub _wstrdate_s
@ stdcall _wstrtime() msvcrt._wstrtime
;@ stub _wstrtime_s
;@ stub _wutime32
@ stdcall _wutime64() msvcrt._wutime64
@ stdcall asctime() msvcrt.asctime
;@ stub asctime_s
@ stdcall clock() msvcrt.clock
@ stdcall strftime() msvcrt.strftime
@ stdcall wcsftime() msvcrt.wcsftime
