
# This file is autogenerated by update.py
@ stdcall __conio_common_vcprintf() msvcrt.__conio_common_vcprintf
@ stdcall __conio_common_vcprintf_p() msvcrt.__conio_common_vcprintf_p
@ stdcall __conio_common_vcprintf_s() msvcrt.__conio_common_vcprintf_s
@ stdcall __conio_common_vcscanf() msvcrt.__conio_common_vcscanf
@ stdcall __conio_common_vcwprintf() msvcrt.__conio_common_vcwprintf
@ stdcall __conio_common_vcwprintf_p() msvcrt.__conio_common_vcwprintf_p
@ stdcall __conio_common_vcwprintf_s() msvcrt.__conio_common_vcwprintf_s
@ stdcall __conio_common_vcwscanf() msvcrt.__conio_common_vcwscanf
@ stdcall _cgets() msvcrt._cgets
;@ stub _cgets_s
;@ stub _cgetws
;@ stub _cgetws_s
@ stdcall _cputs() msvcrt._cputs
@ stdcall _cputws() msvcrt._cputws
@ stdcall _getch() msvcrt._getch
;@ stub _getch_nolock
@ stdcall _getche() msvcrt._getche
;@ stub _getche_nolock
;@ stub _getwch
;@ stub _getwch_nolock
;@ stub _getwche
;@ stub _getwche_nolock
@ stdcall _putch() msvcrt._putch
;@ stub _putch_nolock
@ stdcall _putwch() msvcrt._putwch
;@ stub _putwch_nolock
@ stdcall _ungetch() msvcrt._ungetch
;@ stub _ungetch_nolock
;@ stub _ungetwch
;@ stub _ungetwch_nolock
