
# This file is autogenerated by update.py

@ stdcall -stub __dllonexit3()
@ stdcall __wgetmainargs() msvcrt.__wgetmainargs
@ stdcall _amsg_exit() msvcrt._amsg_exit
@ stdcall _c_exit() msvcrt._c_exit
@ stdcall _cexit() msvcrt._cexit
@ stdcall _exit() msvcrt._exit
@ stdcall _initterm() msvcrt._initterm
@ stdcall -version=0x600+ _initterm_e() msvcrt._initterm_e
@ stdcall -stub _invalid_parameter()
@ stdcall -stub _onexit(ptr)# msvcrt._onexit
@ stdcall _purecall() msvcrt._purecall
@ stdcall _time64() msvcrt._time64
@ extern -stub atexit msvcrt.atexit # the -stub is a HACK to fix VS < 2017 build!
@ stdcall exit() msvcrt.exit
@ stdcall -stub hgets()
@ stdcall -stub hwprintf() 
@ stdcall time() msvcrt.time
@ stdcall wprintf() msvcrt.wprintf
