
# This file is autogenerated by update.py

@ stdcall _aligned_free() msvcrt._aligned_free
@ stdcall _aligned_malloc() msvcrt._aligned_malloc
@ stdcall _aligned_msize() msvcrt._aligned_msize
@ stdcall _aligned_offset_malloc() msvcrt._aligned_offset_malloc
@ stdcall _aligned_offset_realloc() msvcrt._aligned_offset_realloc
@ stdcall _aligned_offset_recalloc() msvcrt._aligned_offset_recalloc
@ stdcall _aligned_realloc() msvcrt._aligned_realloc
@ stdcall _aligned_recalloc() msvcrt._aligned_recalloc
@ stdcall _callnewh() msvcrt._callnewh
@ stdcall _calloc_base() msvcrt._calloc_base
@ stdcall _expand() msvcrt._expand
@ stdcall _free_base() msvcrt._free_base
@ stdcall _get_heap_handle() msvcrt._get_heap_handle
@ stdcall _heapchk() msvcrt._heapchk
@ stdcall _heapmin() msvcrt._heapmin
@ stdcall _heapwalk() msvcrt._heapwalk
@ stdcall _malloc_base() msvcrt._malloc_base
@ stdcall _msize() msvcrt._msize
@ stdcall _query_new_handler() msvcrt._query_new_handler
@ stdcall _query_new_mode() msvcrt._query_new_mode
@ stdcall _realloc_base() msvcrt._realloc_base
@ stdcall _recalloc() msvcrt._recalloc
@ stdcall _set_new_mode() msvcrt._set_new_mode
@ stdcall calloc() msvcrt.calloc
@ stdcall free() msvcrt.free
@ stdcall malloc() msvcrt.malloc
@ stdcall realloc() msvcrt.realloc
