
# This file is autogenerated by update.py

@ stdcall -version=0x600+ CallbackMayRunLong() kernel32.CallbackMayRunLong
@ stdcall -version=0x600+ CancelThreadpoolIo() kernel32.CancelThreadpoolIo
@ stdcall ChangeTimerQueueTimer() kernel32.ChangeTimerQueueTimer
@ stdcall -stub -version=0x600+ CloseThreadpool()
@ stdcall -stub -version=0x600+ CloseThreadpoolCleanupGroup() 
@ stdcall -version=0x600+ CloseThreadpoolCleanupGroupMembers() kernel32.CloseThreadpoolCleanupGroupMembers
@ stdcall -stub -version=0x600+ CloseThreadpoolIo() 
@ stdcall -stub -version=0x600+ CloseThreadpoolTimer()
@ stdcall -stub -version=0x600+ CloseThreadpoolWait() 
@ stdcall -stub -version=0x600+ CloseThreadpoolWork() 
@ stdcall -stub -version=0x600+ CreateThreadpool()
@ stdcall -stub -version=0x600+ CreateThreadpoolCleanupGroup()
@ stdcall -stub -version=0x600+ CreateThreadpoolIo() 
@ stdcall -stub -version=0x600+ CreateThreadpoolTimer() 
@ stdcall -stub -version=0x600+ CreateThreadpoolWait() 
@ stdcall -stub -version=0x600+ CreateThreadpoolWork() 
@ stdcall CreateTimerQueue() kernel32.CreateTimerQueue
@ stdcall CreateTimerQueueTimer() kernel32.CreateTimerQueueTimer
@ stdcall DeleteTimerQueueEx() kernel32.DeleteTimerQueueEx
@ stdcall DeleteTimerQueueTimer() kernel32.DeleteTimerQueueTimer
@ stdcall -version=0x600+ DisassociateCurrentThreadFromCallback() kernel32.DisassociateCurrentThreadFromCallback
@ stdcall -version=0x600+ FreeLibraryWhenCallbackReturns() kernel32.FreeLibraryWhenCallbackReturns
@ stdcall -version=0x600+ IsThreadpoolTimerSet() kernel32.IsThreadpoolTimerSet
@ stdcall -version=0x600+ LeaveCriticalSectionWhenCallbackReturns() kernel32.LeaveCriticalSectionWhenCallbackReturns
@ stub QueryThreadpoolStackInformation
@ stdcall RegisterWaitForSingleObjectEx() kernel32.RegisterWaitForSingleObjectEx
@ stdcall -version=0x600+ ReleaseMutexWhenCallbackReturns() kernel32.ReleaseMutexWhenCallbackReturns
@ stdcall -version=0x600+ ReleaseSemaphoreWhenCallbackReturns() kernel32.ReleaseSemaphoreWhenCallbackReturns
@ stdcall -version=0x600+ SetEventWhenCallbackReturns() kernel32.SetEventWhenCallbackReturns
@ stub SetThreadpoolStackInformation
@ stdcall -version=0x600+ SetThreadpoolThreadMaximum() kernel32.SetThreadpoolThreadMaximum
@ stdcall -version=0x600+ SetThreadpoolThreadMinimum() kernel32.SetThreadpoolThreadMinimum
@ stdcall -version=0x600+ SetThreadpoolTimer() kernel32.SetThreadpoolTimer
@ stdcall -version=0x600+ SetThreadpoolWait() kernel32.SetThreadpoolWait
@ stdcall -version=0x600+ StartThreadpoolIo() kernel32.StartThreadpoolIo
@ stdcall -version=0x600+ SubmitThreadpoolWork() kernel32.SubmitThreadpoolWork
@ stdcall -stub -version=0x600+ TrySubmitThreadpoolCallback() 
@ stdcall UnregisterWaitEx() kernel32.UnregisterWaitEx
@ stdcall -version=0x600+ WaitForThreadpoolIoCallbacks() kernel32.WaitForThreadpoolIoCallbacks
@ stdcall -version=0x600+ WaitForThreadpoolTimerCallbacks() kernel32.WaitForThreadpoolTimerCallbacks
@ stdcall -version=0x600+ WaitForThreadpoolWaitCallbacks() kernel32.WaitForThreadpoolWaitCallbacks
@ stdcall -version=0x600+ WaitForThreadpoolWorkCallbacks() kernel32.WaitForThreadpoolWorkCallbacks
