
# This file is autogenerated by update.py

@ stdcall ___lc_codepage_func() msvcrt.___lc_codepage_func
@ stdcall ___lc_collate_cp_func() msvcrt.___lc_collate_cp_func
@ cdecl ___lc_locale_name_func() msvcrt.___lc_locale_name_func
@ stdcall ___mb_cur_max_func() msvcrt.___mb_cur_max_func
@ stub ___mb_cur_max_l_func
@ stub __initialize_lconv_for_unsigned_char
@ stdcall __pctype_func() msvcrt.__pctype_func
@ stdcall __pwctype_func() msvcrt.__pwctype_func
@ cdecl -version=0x600+ _configthreadlocale(long) msvcrt._configthreadlocale
@ stub _create_locale
@ stub _free_locale
@ stub _get_current_locale
@ stdcall _getmbcp() msvcrt._getmbcp
@ cdecl -version=0x600+ _lock_locales() msvcrt._lock_locales
@ stdcall _setmbcp() msvcrt._setmbcp
@ cdecl -version=0x600+ _unlock_locales() msvcrt._unlock_locales
@ stub _wcreate_locale
@ stdcall _wsetlocale() msvcrt._wsetlocale
@ stdcall localeconv() msvcrt.localeconv
@ stdcall setlocale() msvcrt.setlocale
