
# This file is autogenerated by update.py

@ stdcall PathCleanupSpec() shell32.PathCleanupSpec
@ stdcall PathIsExe() shell32.PathIsExe
@ stdcall SHCreateDirectoryExW() shell32.SHCreateDirectoryExW
@ stdcall SHGetDesktopFolder() shell32.SHGetDesktopFolder
@ stdcall SHGetFileInfoW() shell32.SHGetFileInfoW
@ stdcall SHGetFolderLocation() shell32.SHGetFolderLocation
@ stdcall SHGetFolderPathA() shell32.SHGetFolderPathA
@ stdcall SHGetFolderPathAndSubDirW() shell32.SHGetFolderPathAndSubDirW
@ stdcall SHGetFolderPathW() shell32.SHGetFolderPathW
@ stdcall SHGetInstanceExplorer() shell32.SHGetInstanceExplorer
@ stdcall -stub -version=0x600+ SHGetKnownFolderPath(long long long ptr)
@ stdcall SHGetSpecialFolderPathA() shell32.SHGetSpecialFolderPathA
@ stdcall SHGetSpecialFolderPathW() shell32.SHGetSpecialFolderPathW
@ stdcall -stub -version=0x600+ SHSetKnownFolderPath(long long long ptr)
