
@ stdcall InitOnceExecuteOnce(ptr ptr ptr ptr)
@ stdcall InitOnceBeginInitialize(ptr long ptr ptr)
@ stdcall InitOnceComplete(ptr long ptr)
@ stdcall GetFileInformationByHandleEx(long long ptr long)
@ stdcall -ret64 GetTickCount64()

@ stdcall InitializeSRWLock(ptr)
@ stdcall AcquireSRWLockExclusive(ptr)
@ stdcall AcquireSRWLockShared(ptr)
@ stdcall ReleaseSRWLockExclusive(ptr)
@ stdcall ReleaseSRWLockShared(ptr)

@ stdcall InitializeConditionVariable(ptr)
@ stdcall SleepConditionVariableCS(ptr ptr long)
@ stdcall SleepConditionVariableSRW(ptr ptr long long)
@ stdcall WakeAllConditionVariable(ptr)
@ stdcall WakeConditionVariable(ptr)

@ stdcall InitializeCriticalSectionEx(ptr long long)
@ stdcall ResolveLocaleName(ptr ptr long)
@ stdcall ApplicationRecoveryFinished(long)
@ stdcall ApplicationRecoveryInProgress(ptr)
@ stdcall CreateSymbolicLinkA(str str long)
@ stdcall CreateSymbolicLinkW(wstr wstr long)
@ stdcall GetApplicationRecoveryCallback(ptr ptr ptr ptr ptr)
@ stdcall GetApplicationRestart(ptr wstr ptr ptr)
@ stdcall GetFileBandwidthReservation(ptr ptr ptr ptr ptr ptr)
@ stdcall GetFileMUIInfo(long wstr ptr ptr)
@ stdcall GetFileMUIPath(long wstr wstr ptr wstr ptr ptr)
@ stdcall GetFinalPathNameByHandleA(ptr str long long)
@ stdcall GetFinalPathNameByHandleW(ptr wstr long long)
@ stdcall GetSystemPreferredUILanguages(long ptr wstr ptr)
@ stdcall GetThreadPreferredUILanguages(long ptr wstr ptr)
@ stdcall GetThreadUILanguage()
@ stdcall GetUILanguageInfo(long wstr wstr ptr ptr)
@ stdcall GetUserPreferredUILanguages(long ptr wstr ptr)
@ stdcall OpenFileById(ptr ptr long long ptr long)
@ stdcall QueryFullProcessImageNameA(ptr long str ptr)
@ stdcall QueryFullProcessImageNameW(ptr long wstr ptr)
@ stdcall RegisterApplicationRecoveryCallback(ptr ptr long long)
@ stdcall RegisterApplicationRestart(wstr long)
@ stdcall SetFileBandwidthReservation(ptr long long long ptr ptr)
@ stdcall SetThreadPreferredUILanguages(long wstr ptr)
@ stdcall SetProcessPreferredUILanguages(long ptr ptr)
@ stdcall InitializeProcThreadAttributeList(ptr long long ptr)

@ stdcall   K32EnumDeviceDrivers(ptr long ptr)
@ stdcall -stub K32EnumPageFilesA(ptr ptr)
@ stdcall -stub K32EnumPageFilesW(ptr ptr)
@ stdcall   K32EnumProcessModules(long ptr long ptr)
@ stdcall   K32EnumProcessModulesEx(long ptr long ptr long)
@ stdcall   K32EnumProcesses(ptr long ptr)
@ stdcall   K32GetDeviceDriverBaseNameA(ptr ptr long)
@ stdcall   K32GetDeviceDriverBaseNameW(ptr ptr long)
@ stdcall   K32GetDeviceDriverFileNameA(ptr ptr long)
@ stdcall   K32GetDeviceDriverFileNameW(ptr ptr long)
@ stdcall   K32GetModuleBaseNameA(long long ptr long)
@ stdcall   K32GetModuleBaseNameW(long long ptr long)
@ stdcall   K32GetModuleFileNameExA(long long ptr long)
@ stdcall   K32GetModuleFileNameExW(long long ptr long)
@ stdcall   K32GetModuleInformation(long long ptr long)
@ stdcall   K32GetProcessMemoryInfo(ptr ptr long)
@ stdcall   PowerClearRequest(long long)
@ stdcall   PowerCreateRequest(ptr)
@ stdcall   PowerSetRequest(long long)
@ stdcall   K32GetPerformanceInfo(ptr long)
@ stdcall   K32QueryWorkingSet(ptr ptr long)
@ stdcall   K32QueryWorkingSetEx(ptr ptr long)
@ stdcall   K32GetMappedFileNameW(ptr ptr ptr long)
@ stdcall    QueryUnbiasedInterruptTime(ptr)
@ stdcall CopyContext(ptr long ptr)
@ stdcall GetProcessPreferredUILanguages(long ptr ptr ptr)
@ stdcall DeleteProcThreadAttributeList(ptr)
@ stdcall UpdateProcThreadAttribute(ptr long ptr ptr long ptr ptr)
@ stdcall CallbackMayRunLong(ptr)
@ stdcall CreateThreadpool(ptr)
@ stdcall CreateThreadpoolCleanupGroup()
@ stdcall CreateThreadpoolIo(ptr ptr ptr ptr)
@ stdcall CreateThreadpoolTimer(ptr ptr ptr)
@ stdcall CreateThreadpoolWait(ptr ptr ptr)
@ stdcall CreateThreadpoolWork(ptr ptr ptr)
@ stdcall SetThreadpoolThreadMaximum(ptr long) ntdll.TpSetPoolMaxThreads
@ stdcall SetThreadpoolThreadMinimum(ptr long) ntdll.TpSetPoolMinThreads
@ stdcall SetThreadpoolTimer(ptr ptr long long)
@ stdcall SetThreadpoolWait(ptr long ptr)
@ stdcall TrySubmitThreadpoolCallback(ptr ptr ptr)
@ stdcall CloseThreadpool(ptr) ntdll.TpReleasePool
@ stdcall CloseThreadpoolCleanupGroup(ptr) ntdll.TpReleaseCleanupGroup
@ stdcall CloseThreadpoolCleanupGroupMembers(ptr long ptr) ntdll.TpReleaseCleanupGroupMembers
@ stdcall CloseThreadpoolTimer(ptr) ntdll.TpReleaseTimer
@ stdcall CloseThreadpoolWait(ptr) ntdll.TpReleaseWait
@ stdcall CloseThreadpoolWork(ptr) ntdll.TpReleaseWork

;@ stdcall GetActiveProcessorCount(long)
;@ stdcall GetActiveProcessorGroupCount()
;@ stdcall GetLogicalProcessorInformationEx(ptr ptr ptr)
;@ stdcall GetMaximumProcessorCount(long)
;@ stdcall GetMaximumProcessorGroupCount()
;@ stdcall GetNumaAvailableMemoryNodeEx(long ptr)
;@ stdcall GetNumaNodeNumberFromHandle(long ptr)
;@ stdcall GetNumaNodeProcessorMaskEx(long ptr)
;@ stdcall GetNumaProcessorNodeEx(ptr ptr)
;@ stdcall GetNumaProximityNodeEx(long ptr)
;@ stdcall GetProcessGroupAffinity(long ptr ptr)