/* POSIX+ system calls (machine generated: do not edit!) */
#ifndef _PSX_SYSCALL_H
#define _PSX_SYSCALL_H
#define PSXSS_NULL 0
#define PSXSS_FORK 1
#define PSXSS_AUTHENTICATEUSER 2
#define PSXSS_WAITPID 3
#define PSXSS__EXIT 4
#define PSXSS_KILL 5
#define PSXSS_SIGACTION 6
#define PSXSS_SIGPROCMASK 7
#define PSXSS_SIGPENDING 8
#define PSXSS_SIGSUSPEND 9
#define PSXSS_ALARM 10
#define PSXSS_GETPSIDS 11
#define PSXSS_SYSCALL12 12
#define PSXSS_SYSCALL13 13
#define PSXSS_GETGROUPS 14
#define PSXSS_SYSCALL15 15
#define PSXSS_SYSCALL16 16
#define PSXSS_SETSID 17
#define PSXSS_SETPGID 18
#define PSXSS_SYSCALL19 19
#define PSXSS_SYSCALL20 20
#define PSXSS_TIMES 21
#define PSXSS_TTYNAME 22
#define PSXSS_ISATTY 23
#define PSXSS_SYSCONF 24
#define PSXSS_OPEN 25
#define PSXSS_UMASK 26
#define PSXSS_LINK 27
#define PSXSS_MKDIR 28
#define PSXSS_MKFIFO 29
#define PSXSS_RMDIR 30
#define PSXSS_RENAME 31
#define PSXSS_STAT 32
#define PSXSS_FSTAT 33
#define PSXSS_ACCESS 34
#define PSXSS_CHMOD 35
#define PSXSS_CHOWN 36
#define PSXSS_UTIME 37
#define PSXSS_PATHCONF 38
#define PSXSS_FPATHCONF 39
#define PSXSS_PIPE 40
#define PSXSS_SYSCALL41 41
#define PSXSS_DUP2 42
#define PSXSS_CLOSE 43
#define PSXSS_READ 44
#define PSXSS_WRITE 45
#define PSXSS_FCNTL 46
#define PSXSS_LSEEK 47
#define PSXSS_TCGETATTR 48
#define PSXSS_TCSETATTR 49
#define PSXSS_TCSENDBREAK 50
#define PSXSS_TCDRAIN 51
#define PSXSS_TCFLUSH 52
#define PSXSS_TCFLOW 53
#define PSXSS_TCGETPGRP 54
#define PSXSS_TCSETPGRP 55
#define PSXSS_GETPWUID 56
#define PSXSS_GETPWNAM 57
#define PSXSS_GETGRGID 58
#define PSXSS_GETGRNAM 59
#define PSXSS_UNLINK 60
#define PSXSS_READDIR 61
#define PSXSS_FTRUNCATE 62
#define PSXSS_SYSCALL63 63
#define PSXSS_SEMCTL 64
#define PSXSS_SEMGET 65
#define PSXSS_SEMOP 66
#define PSXSS_SHMAT 67
#define PSXSS_SHMCTL 68
#define PSXSS_SHMDT 69
#define PSXSS_SHMGET 70
#define PSXSS_MSGCTL 71
#define PSXSS_MSGGET 72
#define PSXSS_MSGRCV 73
#define PSXSS_MSGSND 74
#define PSXSS_SOCKET 75
#define PSXSS_ACCEPT 76
#define PSXSS_BIND 77
#define PSXSS_CONNECT 78
#define PSXSS_GETPEERNAME 79
#define PSXSS_GETSOCKNAME 80
#define PSXSS_GETSOCKOPT 81
#define PSXSS_LISTEN 82
#define PSXSS_RECV 83
#define PSXSS_RECVFROM 84
#define PSXSS_SEND 85
#define PSXSS_SENDTO 86
#define PSXSS_SETSOCKOPT 87
#define PSXSS_SHUTDOWN 88
#define PSXSS_GETHOSTBYNAME 89
#define PSXSS_GETHOSTBYADDR 90
#define PSXSS_GETPROTOBYNAME 91
#define PSXSS_GETPROTOBYNUMBER 92
#define PSXSS_GETSERVBYNAME 93
#define PSXSS_GETSERVBYPORT 94
#define PSXSS_SELECT 95
#define PSXSS_STATVFS 96
#define PSXSS_FSTATVFS 97
#define PSXSS_PTSNAME 98
#define PSXSS__FDPTCHECK 99
#define PSXSS_IOCTL 100
#define PSXSS_MMAP 101
#define PSXSS_SYSCALL102 102
#define PSXSS_UIDTONTSID 103
#define PSXSS_GETTZENV 104
#define PSXSS_PUTUTXLINE 105
#define PSXSS_RENAMEWTMPX 106
#define PSXSS_FSYNC 107
#define PSXSS_SETGETITIMER 108
#define PSXSS_SETUSER 109
#define PSXSS_IPCS 110
#define PSX_SYSCALL_APIPORT_COUNT 111
#endif /* ndef _PSX_SYSCALL_H */
/* EOF */
MESSAGE);
NTSTATUS STDCALL syscall_getpwuid (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getpwnam (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getgrgid (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getgrnam (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_unlink (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_readdir (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_ftruncate (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_syscall63 (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_semctl (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_semget (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_semop (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_shmat (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_shmctl (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_shmdt (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_shmget (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_msgctl (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_msgget (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_msgrcv (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_msgsnd (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_socket (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_accept (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_bind (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_connect (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getpeername (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getsockname (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getsockopt (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_listen (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_recv (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_recvfrom (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_send (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_sendto (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_setsockopt (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_shutdown (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_gethostbyname (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_gethostbyaddr (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getprotobyname (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getprotobynumber (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getservbyname (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_getservbyport (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_select (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_statvfs (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_fstatvfs (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_ptsname (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall__fdptcheck (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_ioctl (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_mmap (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_syscall102 (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_uidtontsid (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_gettzenv (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_pututxline (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_renamewtmpx (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_fsync (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_setgetitimer (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_setuser (PPSX_MAX_MESSAGE);
NTSTATUS STDCALL syscall_ipcs (PPSX_MAX_MESSAGE);
#endif /* ndef _SERVER_SYSCALL_H */
/* EOF */
