/*
 * PROJECT:     ReactOS Display Driver Model
 * LICENSE:     MIT (https://spdx.org/licenses/MIT)
 * PURPOSE:     DXGKRNL Windows 8+ interace APIs
 * COPYRIGHT:   Copyright 2023 Justin Miller <justinmiller100@gmail.com>
 */

#include <dxgkrnl.h>
#define NDEBUG
#include <debug.h>

/*
 *   This file is named Win8 but we include windows 10/11 stuff here too for now..
 */
#if 0
#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WIN8)

    DXGKCB_CREATECONTEXTALLOCATION          DxgkCbCreateContextAllocation;
    DXGKCB_DESTROYCONTEXTALLOCATION         DxgkCbDestroyContextAllocation;
    DXGKCB_SETPOWERCOMPONENTACTIVE          DxgkCbSetPowerComponentActive;
    DXGKCB_SETPOWERCOMPONENTIDLE            DxgkCbSetPowerComponentIdle;
   // DXGKCB_ACQUIRE_POST_DISPLAY_OWNERSHIP   DxgkCbAcquirePostDisplayOwnership;
    DXGKCB_POWERRUNTIMECONTROLREQUEST       DxgkCbPowerRuntimeControlRequest;
    DXGKCB_SETPOWERCOMPONENTLATENCY         DxgkCbSetPowerComponentLatency;
    DXGKCB_SETPOWERCOMPONENTRESIDENCY       DxgkCbSetPowerComponentResidency;
    DXGKCB_COMPLETEFSTATETRANSITION         DxgkCbCompleteFStateTransition;

#endif // DXGKDDI_INTERFACE_VERSION

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM1_3)

    DXGKCB_COMPLETEPSTATETRANSITION         DxgkCbCompletePStateTransition;

#endif // DXGKDDI_INTERFACE_VERSION_WDDM1_3

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_0)

    DXGKCB_MAPCONTEXTALLOCATION             DxgkCbMapContextAllocation;
    DXGKCB_UPDATECONTEXTALLOCATION          DxgkCbUpdateContextAllocation;
    DXGKCB_RESERVEGPUVIRTUALADDRESSRANGE    DxgkCbReserveGpuVirtualAddressRange;
    DXGKCB_ACQUIREHANDLEDATA                DxgkCbAcquireHandleData;
    DXGKCB_RELEASEHANDLEDATA                DxgkCbReleaseHandleData;
    DXGKCB_HARDWARECONTENTPROTECTIONTEARDOWN DxgkCbHardwareContentProtectionTeardown;

#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_0)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_1)

    DXGKCB_MULTIPLANEOVERLAYDISABLED        DxgkCbMultiPlaneOverlayDisabled;
    DXGKCB_DXGKCB_MITIGATEDRANGEUPDATE      DxgkCbMitigatedRangeUpdate;

#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_1)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_2)

    DXGKCB_INVALIDATEHWCONTEXT              DxgkCbInvalidateHwContext;
    DXGKCB_INDICATE_CONNECTOR_CHANGE        DxgkCbIndicateConnectorChange;
    DXGKCB_UNBLOCKUEFIFRAMEBUFFERRANGES     DxgkCbUnblockUEFIFrameBufferRanges;
   // DXGKCB_ACQUIRE_POST_DISPLAY_OWNERSHIP2  DxgkCbAcquirePostDisplayOwnership2;

#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_2)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_3)

    DXGKCB_SETPROTECTEDSESSIONSTATUS        DxgkCbSetProtectedSessionStatus;

#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_3)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_4)
    DXGKCB_ALLOCATECONTIGUOUSMEMORY         DxgkCbAllocateContiguousMemory;
    DXGKCB_FREECONTIGUOUSMEMORY             DxgkCbFreeContiguousMemory;
    DXGKCB_ALLOCATEPAGESFORMDL              DxgkCbAllocatePagesForMdl;
    DXGKCB_FREEPAGESFROMMDL                 DxgkCbFreePagesFromMdl;
    DXGKCB_PINFRAMEBUFFERFORSAVE            DxgkCbPinFrameBufferForSave;
    DXGKCB_UNPINFRAMEBUFFERFORSAVE          DxgkCbUnpinFrameBufferForSave;
    DXGKCB_MAPFRAMEBUFFERPOINTER            DxgkCbMapFrameBufferPointer;
    DXGKCB_UNMAPFRAMEBUFFERPOINTER          DxgkCbUnmapFrameBufferPointer;
    DXGKCB_MAPMDLTOIOMMU                    DxgkCbMapMdlToIoMmu;
    DXGKCB_UNMAPMDLFROMIOMMU                DxgkCbUnmapMdlFromIoMmu;
   // DXGKCB_REPORT_DIAGNOSTIC                DxgkCbReportDiagnostic;
#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_4)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_5)
    DXGKCB_SIGNALEVENT                      DxgkCbSignalEvent;
#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_5)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_6)
    DXGKCB_ISFEATUREENABLED                 DxgkCbIsFeatureEnabled;
    DXGKCB_SAVEMEMORYFORHOTUPDATE           DxgkCbSaveMemoryForHotUpdate;
#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_6)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_8)
    DXGKCB_NOTIFYCURSORSUPPORTCHANGE        DxgkCbNotifyCursorSupportChange;
#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_8)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_9)
    DXGKCB_QUERYFEATURESUPPORT              DxgkCbQueryFeatureSupport;
    DXGKCB_CREATEPHYSICALMEMORYOBJECT       DxgkCbCreatePhysicalMemoryObject;
    DXGKCB_DESTROYPHYSICALMEMORYOBJECT      DxgkCbDestroyPhysicalMemoryObject;
    DXGKCB_MAPPHYSICALMEMORY                DxgkCbMapPhysicalMemory;
    DXGKCB_UNMAPPHYSICALMEMORY              DxgkCbUnmapPhysicalMemory;
    DXGKCB_ALLOCATEADL                      DxgkCbAllocateAdl;
    DXGKCB_FREEADL                          DxgkCbFreeAdl;
    DXGKCB_OPENPHYSICALMEMORYOBJECT         DxgkCbOpenPhysicalMemoryObject;
    DXGKCB_CLOSEPHYSICALMEMORYOBJECT        DxgkCbClosePhysicalMemoryObject;
    DXGKCB_PINFRAMEBUFFERFORSAVE2           DxgkCbPinFrameBufferForSave2;
#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_9)

#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM3_1)
    DXGKCB_DISCONNECTDOORBELL               DxgkCbDisconnectDoorbell;
#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM3_1)
#endif