@ stub XActivateScreenSaver
@ stub XAddConnectionWatch
@ stub XAddExtension
@ stub XAddHost
@ stub XAddHosts
@ stub XAddPixel
@ stub XAddToExtensionList
@ stub XAddToSaveSet
@ stub XAllPlanes
@ stub XAllocClassHint
@ stub XAllocColor
@ stub XAllocColorCells
@ stub XAllocColorPlanes
@ stub XAllocIconSize
@ stub XAllocNamedColor
@ stub XAllocSizeHints
@ stub XAllocStandardColormap
@ stub XAllocWMHints
@ stub XAllowEvents
@ stub XAutoRepeatOff
@ stub XAutoRepeatOn
@ stub XBaseFontNameListOfFontSet
@ stub XBell
@ stub XBitmapBitOrder
@ stub XBitmapPad
@ stub XBitmapUnit
@ stub XBlackPixel
@ stub XBlackPixelOfScreen
@ stub XCellsOfScreen
@ stub XChangeActivePointerGrab
@ stub XChangeGC
@ stub XChangeKeyboardControl
@ stub XChangeKeyboardMapping
@ stub XChangePointerControl
@ stub XChangeProperty
@ stub XChangeSaveSet
@ stub XChangeWindowAttributes
@ stub XCheckIfEvent
@ stub XCheckMaskEvent
@ stub XCheckTypedEvent
@ stub XCheckTypedWindowEvent
@ stub XCheckWindowEvent
@ stub XCirculateSubwindows
@ stub XCirculateSubwindowsDown
@ stub XCirculateSubwindowsUp
@ stub XClearArea
@ stub XClearWindow
@ stub XClipBox
@ stub XCloseDisplay
@ stub XCloseIM
@ stub XCloseOM
@ stub XConfigureWindow
@ stub XConnectionNumber
@ stub XContextDependentDrawing
@ stub XContextualDrawing
@ stub XConvertCase
@ stub XConvertSelection
@ stub XCopyArea
@ stub XCopyColormapAndFree
@ stub XCopyGC
@ stub XCopyPlane
@ stub XCreateBitmapFromData
@ stub XCreateColormap
@ stub XCreateFontCursor
@ stub XCreateFontSet
@ stub XCreateGC
@ stub XCreateGlyphCursor
@ stub XCreateIC
@ stub XCreateImage
@ stub XCreateOC
@ stub XCreatePixmap
@ stub XCreatePixmapCursor
@ stub XCreatePixmapFromBitmapData
@ stub XCreateRegion
@ stub XCreateSimpleWindow
@ stub XCreateWindow
@ stub XDefaultColormap
@ stub XDefaultColormapOfScreen
@ stub XDefaultDepth
@ stub XDefaultDepthOfScreen
@ stub XDefaultGC
@ stub XDefaultGCOfScreen
@ stub XDefaultRootWindow
@ stub XDefaultScreen
@ stub XDefaultScreenOfDisplay
@ stub XDefaultString
@ stub XDefaultVisual
@ stub XDefaultVisualOfScreen
@ stub XDefineCursor
@ stub XDeleteContext
@ stub XDeleteModifiermapEntry
@ stub XDeleteProperty
@ stub XDestroyIC
@ stub XDestroyImage
@ stub XDestroyOC
@ stub XDestroyRegion
@ stub XDestroySubwindows
@ stub XDestroyWindow
@ stub XDirectionalDependentDrawing
@ stub XDisableAccessControl
@ stub XDisplayCells
@ stub XDisplayHeight
@ stub XDisplayHeightMM
@ stub XDisplayKeycodes
@ stub XDisplayMotionBufferSize
@ stub XDisplayName
@ stub XDisplayOfIM
@ stub XDisplayOfOM
@ stub XDisplayOfScreen
@ stub XDisplayPlanes
@ stub XDisplayString
@ stub XDisplayWidth
@ stub XDisplayWidthMM
@ stub XDoesBackingStore
@ stub XDoesSaveUnders
@ stub XDrawArc
@ stub XDrawArcs
@ stub XDrawImageString
@ stub XDrawImageString16
@ stub XDrawLine
@ stub XDrawLines
@ stub XDrawPoint
@ stub XDrawPoints
@ stub XDrawRectangle
@ stub XDrawRectangles
@ stub XDrawSegments
@ stub XDrawString
@ stub XDrawString16
@ stub XDrawText
@ stub XDrawText16
@ stub XEHeadOfExtensionList
@ stub XESetBeforeFlush
@ stub XESetCloseDisplay
@ stub XESetCopyGC
@ stub XESetCreateFont
@ stub XESetCreateGC
@ stub XESetError
@ stub XESetErrorString
@ stub XESetEventToWire
@ stub XESetFlushGC
@ stub XESetFreeFont
@ stub XESetFreeGC
@ stub XESetPrintErrorValues
@ stub XESetWireToError
@ stub XESetWireToEvent
@ stub XEmptyRegion
@ stub XEnableAccessControl
@ stub XEqualRegion
@ stub XEventMaskOfScreen
@ stub XEventsQueued
@ stub XExtendedMaxRequestSize
@ stub XExtentsOfFontSet
@ stub XFetchBuffer
@ stub XFetchBytes
@ stub XFetchName
@ stub XFillArc
@ stub XFillArcs
@ stub XFillPolygon
@ stub XFillRectangle
@ stub XFillRectangles
@ stub XFilterEvent
@ stub XFindContext
@ stub XFindOnExtensionList
@ stub XFlush
@ stub XFlushGC
@ stub XFontsOfFontSet
@ stub XForceScreenSaver
@ stub XFree
@ stub XFreeColormap
@ stub XFreeColors
@ stub XFreeCursor
@ stub XFreeExtensionList
@ stub XFreeFont
@ stub XFreeFontInfo
@ stub XFreeFontNames
@ stub XFreeFontPath
@ stub XFreeFontSet
@ stub XFreeGC
@ stub XFreeModifiermap
@ stub XFreePixmap
@ stub XFreeStringList
@ stub XGContextFromGC
@ stub XGeometry
@ stub XGetAtomName
@ stub XGetAtomNames
@ stub XGetClassHint
@ stub XGetCommand
@ stub XGetDefault
@ stub XGetErrorDatabaseText
@ stub XGetErrorText
@ stub XGetFontPath
@ stub XGetFontProperty
@ stub XGetGCValues
@ stub XGetGeometry
@ stub XGetICValues
@ stub XGetIMValues
@ stub XGetIconName
@ stub XGetIconSizes
@ stub XGetImage
@ stub XGetInputFocus
@ stub XGetKeyboardControl
@ stub XGetKeyboardMapping
@ stub XGetModifierMapping
@ stub XGetMotionEvents
@ stub XGetNormalHints
@ stub XGetOCValues
@ stub XGetOMValues
@ stub XGetPixel
@ stub XGetPointerControl
@ stub XGetPointerMapping
@ stub XGetRGBColormaps
@ stub XGetScreenSaver
@ stub XGetSelectionOwner
@ stub XGetSizeHints
@ stub XGetStandardColormap
@ stub XGetSubImage
@ stub XGetTextProperty
@ stub XGetTransientForHint
@ stub XGetVisualInfo
@ stub XGetWMClientMachine
@ stub XGetWMColormapWindows
@ stub XGetWMHints
@ stub XGetWMIconName
@ stub XGetWMName
@ stub XGetWMNormalHints
@ stub XGetWMProtocols
@ stub XGetWMSizeHints
@ stub XGetWindowAttributes
@ stub XGetWindowProperty
@ stub XGetZoomHints
@ stub XGrabButton
@ stub XGrabKey
@ stub XGrabKeyboard
@ stub XGrabPointer
@ stub XGrabServer
@ stub XHeightMMOfScreen
@ stub XHeightOfScreen
@ stub XIMOfIC
@ stub XIconifyWindow
@ stub XIfEvent
@ stub XImageByteOrder
@ stub XInitExtension
@ stub XInitImage
@ stub XInitThreads
@ stub XInsertModifiermapEntry
@ stub XInstallColormap
@ stub XInternAtom
@ stub XInternAtoms
@ stub XInternalConnectionNumbers
@ stub XIntersectRegion
@ stub XKeycodeToKeysym
@ stub XKeysymToKeycode
@ stub XKeysymToString
@ stub XKillClient
@ stub XLastKnownRequestProcessed
@ stub XListDepths
@ stub XListExtensions
@ stub XListFonts
@ stub XListFontsWithInfo
@ stub XListHosts
@ stub XListInstalledColormaps
@ stub XListPixmapFormats
@ stub XListProperties
@ stub XLoadFont
@ stub XLoadQueryFont
@ stub XLocaleOfFontSet
@ stub XLocaleOfIM
@ stub XLocaleOfOM
@ stub XLockDisplay
@ stub XLookupColor
@ stub XLookupKeysym
@ stub XLookupString
@ stub XLowerWindow
@ stub XMapRaised
@ stub XMapSubwindows
@ stub XMapWindow
@ stub XMaskEvent
@ stub XMatchVisualInfo
@ stub XMaxCmapsOfScreen
@ stub XMaxRequestSize
@ stub XMinCmapsOfScreen
@ stub XMoveResizeWindow
@ stub XMoveWindow
@ stub XNewModifiermap
@ stub XNextEvent
@ stub XNextRequest
@ stub XNoOp
@ stub XOMOfOC
@ stub XOffsetRegion
@ stub XOpenDisplay
@ stub XOpenIM
@ stub XOpenOM
@ stub XParseColor
@ stub XParseGeometry
@ stub XPeekEvent
@ stub XPeekIfEvent
@ stub XPending
@ stub XPlanesOfScreen
@ stub XPointInRegion
@ stub XPolygonRegion
@ stub XProcessInternalConnection
@ stub XProtocolRevision
@ stub XProtocolVersion
@ stub XPutBackEvent
@ stub XPutImage
@ stub XPutPixel
@ stub XQLength
@ stub XQueryBestCursor
@ stub XQueryBestSize
@ stub XQueryBestStipple
@ stub XQueryBestTile
@ stub XQueryColor
@ stub XQueryColors
@ stub XQueryExtension
@ stub XQueryFont
@ stub XQueryKeymap
@ stub XQueryPointer
@ stub XQueryTextExtents
@ stub XQueryTextExtents16
@ stub XQueryTree
@ stub XRaiseWindow
@ stub XReadBitmapFile
@ stub XReadBitmapFileData
@ stub XRebindKeysym
@ stub XRecolorCursor
@ stub XReconfigureWMWindow
@ stub XRectInRegion
@ stub XRefreshKeyboardMapping
@ stub XRegisterIMInstantiateCallback
@ stub XRemoveConnectionWatch
@ stub XRemoveFromSaveSet
@ stub XRemoveHost
@ stub XRemoveHosts
@ stub XReparentWindow
@ stub XResetScreenSaver
@ stub XResizeWindow
@ stub XResourceManagerString
@ stub XRestackWindows
@ stub XRootWindow
@ stub XRootWindowOfScreen
@ stub XRotateBuffers
@ stub XRotateWindowProperties
@ stub XSaveContext
@ stub XScreenCount
@ stub XScreenNumberOfScreen
@ stub XScreenOfDisplay
@ stub XScreenResourceString
@ stub XSelectInput
@ stub XSendEvent
@ stub XServerVendor
@ stub XSetAccessControl
@ stub XSetAfterFunction
@ stub XSetArcMode
@ stub XSetAuthorization
@ stub XSetBackground
@ stub XSetClassHint
@ stub XSetClipMask
@ stub XSetClipOrigin
@ stub XSetClipRectangles
@ stub XSetCloseDownMode
@ stub XSetCommand
@ stub XSetDashes
@ stub XSetErrorHandler
@ stub XSetFillRule
@ stub XSetFillStyle
@ stub XSetFont
@ stub XSetFontPath
@ stub XSetForeground
@ stub XSetFunction
@ stub XSetGraphicsExposures
@ stub XSetICFocus
@ stub XSetICValues
@ stub XSetIMValues
@ stub XSetIOErrorHandler
@ stub XSetIconName
@ stub XSetIconSizes
@ stub XSetInputFocus
@ stub XSetLineAttributes
@ stub XSetLocaleModifiers
@ stub XSetModifierMapping
@ stub XSetNormalHints
@ stub XSetOCValues
@ stub XSetOMValues
@ stub XSetPlaneMask
@ stub XSetPointerMapping
@ stub XSetRGBColormaps
@ stub XSetRegion
@ stub XSetScreenSaver
@ stub XSetSelectionOwner
@ stub XSetSizeHints
@ stub XSetStandardColormap
@ stub XSetStandardProperties
@ stub XSetState
@ stub XSetStipple
@ stub XSetSubwindowMode
@ stub XSetTSOrigin
@ stub XSetTextProperty
@ stub XSetTile
@ stub XSetTransientForHint
@ stub XSetWMClientMachine
@ stub XSetWMColormapWindows
@ stub XSetWMHints
@ stub XSetWMIconName
@ stub XSetWMName
@ stub XSetWMNormalHints
@ stub XSetWMProperties
@ stub XSetWMProtocols
@ stub XSetWMSizeHints
@ stub XSetWindowBackground
@ stub XSetWindowBackgroundPixmap
@ stub XSetWindowBorder
@ stub XSetWindowBorderPixmap
@ stub XSetWindowBorderWidth
@ stub XSetWindowColormap
@ stub XSetZoomHints
@ stub XShrinkRegion
@ stub XStoreBuffer
@ stub XStoreBytes
@ stub XStoreColor
@ stub XStoreColors
@ stub XStoreName
@ stub XStoreNamedColor
@ stub XStringListToTextProperty
@ stub XStringToKeysym
@ stub XSubImage
@ stub XSubtractRegion
@ stub XSupportsLocale
@ stub XSync
@ stub XSynchronize
@ stub XTextExtents
@ stub XTextExtents16
@ stub XTextPropertyToStringList
@ stub XTextWidth
@ stub XTextWidth16
@ stub XTranslateCoordinates
@ stub XUndefineCursor
@ stub XUngrabButton
@ stub XUngrabKey
@ stub XUngrabKeyboard
@ stub XUngrabPointer
@ stub XUngrabServer
@ stub XUninstallColormap
@ stub XUnionRectWithRegion
@ stub XUnionRegion
@ stub XUnloadFont
@ stub XUnlockDisplay
@ stub XUnmapSubwindows
@ stub XUnmapWindow
@ stub XUnregisterIMInstantiateCallback
@ stub XUnsetICFocus
@ stub XVaCreateNestedList
@ stub XVendorRelease
@ stub XVisualIDFromVisual
@ stub XWMGeometry
@ stub XWarpPointer
@ stub XWhitePixel
@ stub XWhitePixelOfScreen
@ stub XWidthMMOfScreen
@ stub XWidthOfScreen
@ stub XWindowEvent
@ stub XWithdrawWindow
@ stub XWriteBitmapFile
@ stub XXorRegion
@ stub XcmsAddColorSpace
@ stub XcmsAddFunctionSet
@ stub XcmsAllocColor
@ stub XcmsAllocNamedColor
@ stub XcmsCCCOfColormap
@ stub XcmsCIELabClipL
@ stub XcmsCIELabClipLab
@ stub XcmsCIELabClipab
@ stub XcmsCIELabQueryMaxC
@ stub XcmsCIELabQueryMaxL
@ stub XcmsCIELabQueryMaxLC
@ stub XcmsCIELabQueryMinL
@ stub XcmsCIELabToCIEXYZ
@ stub XcmsCIELabWhiteShiftColors
@ stub XcmsCIELuvClipL
@ stub XcmsCIELuvClipLuv
@ stub XcmsCIELuvClipuv
@ stub XcmsCIELuvQueryMaxC
@ stub XcmsCIELuvQueryMaxL
@ stub XcmsCIELuvQueryMaxLC
@ stub XcmsCIELuvQueryMinL
@ stub XcmsCIELuvToCIEuvY
@ stub XcmsCIELuvWhiteShiftColors
@ stub XcmsCIEXYZToCIELab
@ stub XcmsCIEXYZToCIEuvY
@ stub XcmsCIEXYZToCIExyY
@ stub XcmsCIEXYZToRGBi
@ stub XcmsCIEuvYToCIELuv
@ stub XcmsCIEuvYToCIEXYZ
@ stub XcmsCIEuvYToTekHVC
@ stub XcmsCIExyYToCIEXYZ
@ stub XcmsClientWhitePointOfCCC
@ stub XcmsConvertColors
@ stub XcmsCreateCCC
@ stub XcmsDefaultCCC
@ stub XcmsDisplayOfCCC
@ stub XcmsFormatOfPrefix
@ stub XcmsFreeCCC
@ stub XcmsLookupColor
@ stub XcmsPrefixOfFormat
@ stub XcmsQueryBlack
@ stub XcmsQueryBlue
@ stub XcmsQueryColor
@ stub XcmsQueryColors
@ stub XcmsQueryGreen
@ stub XcmsQueryRed
@ stub XcmsQueryWhite
@ stub XcmsRGBToRGBi
@ stub XcmsRGBiToCIEXYZ
@ stub XcmsRGBiToRGB
@ stub XcmsScreenNumberOfCCC
@ stub XcmsScreenWhitePointOfCCC
@ stub XcmsSetCCCOfColormap
@ stub XcmsSetCompressionProc
@ stub XcmsSetWhiteAdjustProc
@ stub XcmsSetWhitePoint
@ stub XcmsStoreColor
@ stub XcmsStoreColors
@ stub XcmsTekHVCClipC
@ stub XcmsTekHVCClipV
@ stub XcmsTekHVCClipVC
@ stub XcmsTekHVCQueryMaxC
@ stub XcmsTekHVCQueryMaxV
@ stub XcmsTekHVCQueryMaxVC
@ stub XcmsTekHVCQueryMaxVSamples
@ stub XcmsTekHVCQueryMinV
@ stub XcmsTekHVCToCIEuvY
@ stub XcmsTekHVCWhiteShiftColors
@ stub XcmsVisualOfCCC
@ stub XmbDrawImageString
@ stub XmbDrawString
@ stub XmbDrawText
@ stub XmbLookupString
@ stub XmbResetIC
@ stub XmbSetWMProperties
@ stub XmbTextEscapement
@ stub XmbTextExtents
@ stub XmbTextListToTextProperty
@ stub XmbTextPerCharExtents
@ stub XmbTextPropertyToTextList
@ stub Xpermalloc
@ stub XrmCombineDatabase
@ stub XrmCombineFileDatabase
@ stub XrmDestroyDatabase
@ stub XrmEnumerateDatabase
@ stub XrmGetDatabase
@ stub XrmGetFileDatabase
@ stub XrmGetResource
@ stub XrmGetStringDatabase
@ stub XrmInitialize
@ stub XrmLocaleOfDatabase
@ stub XrmMergeDatabases
@ stub XrmParseCommand
@ stub XrmPermStringToQuark
@ stub XrmPutFileDatabase
@ stub XrmPutLineResource
@ stub XrmPutResource
@ stub XrmPutStringResource
@ stub XrmQGetResource
@ stub XrmQGetSearchList
@ stub XrmQGetSearchResource
@ stub XrmQPutResource
@ stub XrmQPutStringResource
@ stub XrmQuarkToString
@ stub XrmSetDatabase
@ stub XrmStringToBindingQuarkList
@ stub XrmStringToQuark
@ stub XrmStringToQuarkList
@ stub XrmUniqueQuark
@ stub XwcDrawImageString
@ stub XwcDrawString
@ stub XwcDrawText
@ stub XwcFreeStringList
@ stub XwcLookupString
@ stub XwcResetIC
@ stub XwcTextEscapement
@ stub XwcTextExtents
@ stub XwcTextListToTextProperty
@ stub XwcTextPerCharExtents
@ stub XwcTextPropertyToTextList
@ stub _XAllocID
@ stub _XAllocIDs
@ stub _XAllocScratch
@ stub _XAllocTemp
@ stub _XAsyncErrorHandler
@ stub _XConnectDisplay
@ stub _XCreateMutex_fn_p
@ stub _XDeqAsyncHandler
@ stub _XEatData
@ stub _XError
@ stub _XFlushGCCache
@ stub _XFlushIt
@ stub _XFreeMutex_fn_p
@ stub _XFreeTemp
@ stub _XGetAsyncData
@ stub _XGetAsyncReply
@ stub _XIOError
@ stub _XInitImageFuncPtrs
@ stub _XKillTimer
@ stub _XLockMutex_fn_p
@ stub _XRead
@ stub _XReadEvents
@ stub _XReadPad
@ stub _XRegisterFilterByMask
@ stub _XRegisterFilterByType
@ stub _XRegisterInternalConnection
@ stub _XReply
@ stub _XSend
@ stub _XSetLastRequestRead
@ stub _XSetTimer
@ stub _XUnknownNativeEvent
@ stub _XUnlockMutex_fn_p
@ stub _XUnregisterFilter
@ stub _XUnregisterInternalConnection
@ stub _XVIDtoVisual
@ stub _XWinSelectWindow
@ stub _Xdebug_p
@ stub _Xglobal_lock_p
@ stub _Xthread_init
@ stub _Xthread_waiter