@ stdcall -stub DirectInputCreateA(long long ptr ptr)
@ stdcall -stub DirectInputCreateEx(long long ptr ptr ptr)
@ stdcall -stub DirectInputCreateW(long long ptr ptr)
@ stdcall -stub -private DllCanUnloadNow()
@ stdcall -stub -private DllGetClassObject(ptr ptr ptr)
@ stdcall -stub -private DllRegisterServer()
@ stdcall -stub -private DllUnregisterServer()
