; These are okay to leave as @ stub until good definietons are made.

@ stub IMILBitmapEffectConnector_IsConnected
@ stub IMILBitmapEffectInputConnector_ConnectTo
@ stub IMILBitmapEffectInputConnector_GetConnection
@ stub IMILBitmapEffectOutputConnector_GetConnection
@ stub IMILBitmapEffectOutputConnector_GetNumberConnections
@ stub IMILBitmapEffectRenderContext_GetFinalTransform
@ stub IMILBitmapEffectRenderContext_GetOutputDPI
@ stub IMILBitmapEffectRenderContext_GetOutputPixelFormat
@ stub IMILBitmapEffectRenderContext_SetInitialTransform
@ stub IMILBitmapEffectRenderContext_SetOutputDPI
@ stub IMILBitmapEffectRenderContext_SetOutputPixelFormat
@ stub IMILBitmapEffectRenderContext_SetRegionOfInterest
@ stub IMILBitmapEffectRenderContext_SetUseSoftwareRenderer
@ stub IMILBitmapEffect_GetOutput
@ stub IMILBitmapEffect_GetParentEffect
@ stub IMILBitmapEffect_IMILBitmapEffectConnectionsInfo_GetNumberInputs
@ stub IMILBitmapEffect_IMILBitmapEffectConnectionsInfo_GetNumberOutputs
@ stub IMILBitmapEffect_IMILBitmapEffectConnections_GetInputConnector
@ stub IMILBitmapEffect_IMILBitmapEffectConnections_GetOutputConnector
@ stub IMILBitmapEffect_IMILBitmapEffectGroup_Add
@ stub IMILBitmapEffect_IMILBitmapEffectGroup_GetInteriorInputConnector
@ stub IMILBitmapEffect_IMILBitmapEffectGroup_GetInteriorOutputConnector
@ stub IMILBitmapEffect_IMILBitmapEffectPrimitive_GetAffineMatrix
@ stub IMILBitmapEffect_IMILBitmapEffectPrimitive_HasAffineTransform
@ stub IMILBitmapEffect_IMILBitmapEffectPrimitive_HasInverseTransform
@ stub IMILBitmapEffect_IMILBitmapEffectPrimitive_SetValue
@ stub IMILBitmapEffect_IMILBitmapEffectPrimitive_TransformPoint
@ stub IMILBitmapEffect_IMILBitmapEffectPrimitive_TransformRect
@ stub IMILBitmapEffect_SetInputSource
@ stub MIL3DCalcBrushToIdealSampleSpace
@ stub MIL3DCalcProjected2DBounds
@ stub MILAddRef
@ stub MILCreateBitmapEffectOuterPublic
@ stub MILCreateEventProxy
@ stub MILCreateStreamFromStreamDescriptor
@ stub MILFactoryCreateBitmapEffect
@ stub MILFactoryCreateBitmapEffectContext
@ stub MILFactoryCreateBitmapEffectOuter
@ stub MILFactoryCreateBitmapRenderTarget
@ stub MILFactoryCreateMediaPlayer
@ stub MILFactoryCreateSWRenderTargetForBitmap
@ stub MILIStreamWrite
@ stub MILInitializeBitmapEffectPublic
@ stub MILLoadResource
@ stub MILMediaCanPause
@ stub MILMediaClose
@ stub MILMediaGetBufferingProgress
@ stub MILMediaGetDownloadProgress
@ stub MILMediaGetMediaLength
@ stub MILMediaGetNaturalHeight
@ stub MILMediaGetNaturalWidth
@ stub MILMediaGetPosition
@ stub MILMediaHasAudio
@ stub MILMediaHasVideo
@ stub MILMediaIsBuffering
@ stub MILMediaNeedUIFrameUpdate
@ stub MILMediaOpen
@ stub MILMediaProcessExitHandler
@ stub MILMediaSetBalance
@ stub MILMediaSetIsScrubbingEnabled
@ stub MILMediaSetPosition
@ stub MILMediaSetRate
@ stub MILMediaSetVolume
@ stub MILMediaShutdown
@ stub MILMediaStop
@ stub MILQueryInterface
@ stub MILRegisterWmpFactory
@ stub MILRelease
@ stub MILRenderTargetBitmapClear
@ stub MILRenderTargetBitmapGetBitmap
@ stub MILStreamNotifyReadComplete
@ stub MILUpdateSystemParametersInfo
@ stub MilChannel_AppendCommandData
@ stub MilChannel_BeginCommand
@ stub MilChannel_CommitChannel
@ stub MilChannel_EndCommand
@ stub MilChannel_GetMarshalType
@ stub MilChannel_SendSyncCommand
@ stub MilChannel_SetNotificationWindow
@ stub MilChannel_SetReceiveBroadcastMessages
@ stub MilCompositionEngine_DeinitializePartitionManager
@ stub MilCompositionEngine_EnterCompositionEngineLock
@ stub MilCompositionEngine_ExitCompositionEngineLock
@ stub MilCompositionEngine_GetComposedEventId
@ stub MilCompositionEngine_GetFeedbackReader
@ stub MilCompositionEngine_InitializePartitionManager
@ stub MilCompositionEngine_UpdateSchedulerSettings
@ stub MilComposition_PeekNextMessage
@ stub MilComposition_SyncFlush
@ stub MilComposition_WaitForNextMessage
@ stub MilConnection_CreateChannel
@ stub MilConnection_DestroyChannel
@ stub MilConnection_RecordUCE
@ stub MilContent_AttachToHwnd
@ stub MilContent_DetachFromHwnd
@ stub MilCoreClientIsDwm
@ stub MilGraphicsStream_Close
@ stub MilGraphicsStream_GetTransformHint
@ stub MilGraphicsStream_Open
@ stub MilGraphicsStream_SetTransformHint
@ stub MilPlayer_Create
@ stub MilPlayer_Process
@ stub MilResource_CreateOrAddRefOnChannel
@ stub MilResource_DuplicateHandle
@ stub MilResource_ReleaseOnChannel
@ stub MilResource_SendCommand
@ stub MilResource_SendCommandBitmapSource
@ stub MilResource_SendCommandMedia
@ stub MilSyncPacketTransport_Create
@ stub MilSyncPacketTransport_Present
@ stub MilTransport_AddRef
@ stub MilTransport_Create
@ stub MilTransport_CreateFromPacketTransport
@ stub MilTransport_CreateSurfaceManager
@ stub MilTransport_CreateTransportParameters
@ stub MilTransport_DisconnectTransport
@ stub MilTransport_InitializeConnectionManager
@ stub MilTransport_Release
@ stub MilTransport_ShutDownConnectionManager
@ stub MilUtility_ArcToBezier
@ stub MilUtility_GeometryGetArea
@ stub MilUtility_GetPointAtLengthFraction
@ stub MilUtility_GetTileBrushMapping
@ stub MilUtility_PathGeometryBounds
@ stub MilUtility_PathGeometryCombine
@ stub MilUtility_PathGeometryFlatten
@ stub MilUtility_PathGeometryHitTest
@ stub MilUtility_PathGeometryHitTestPathGeometry
@ stub MilUtility_PathGeometryOutline
@ stub MilUtility_PathGeometryWiden
@ stub MilUtility_PolygonBounds
@ stub MilUtility_PolygonHitTest
@ stub MilVersionCheck
@ stub MilVisualTarget_AttachToHwnd
@ stub MilVisualTarget_DetachFromHwnd
@ stub SetMilPerfInstrumentationFlags
@ stub VirtualChannelGetInstance
@ stub MILCreateFactory
