@ stdcall -stub -version=0x600+ DwmDefWindowProc(ptr long long long ptr)
@ stdcall -stub -version=0x600+ DwmEnableBlurBehindWindow(ptr ptr)
@ stdcall -stub -version=0x600+ DwmExtendFrameIntoClientArea(ptr ptr)
@ stub -version=0x600+ DwmGetGraphicsStreamClient
@ stub -version=0x600+ DwmGetGraphicsStreamTransformHint
@ stub -version=0x600+ DwmGetTransportAttributes
@ stub -version=0x600+ DwmGetWindowAttribute
@ stub -version=0x601+ DwmInvalidateIconicBitmaps
@ stdcall -stub -version=0x600+ DwmIsCompositionEnabled(ptr)
@ stub -version=0x600+ DwmModifyPreviousDxFrameDuration
@ stub -version=0x601+ DwmpActivateLivePreview
@ stub -version=0x600+ DwmpCloseGraphicsStream
@ stub -version=0x601+ DwmpDxBindSwapChain
@ stub -version=0x600+ DwmpDxGetWindowSharedSurface
@ stub -version=0x601+ DwmpDxgiDisableRedirection
@ stub -version=0x601+ DwmpDxgiEnableRedirection
@ stub -version=0x601+ DwmpDxgiIsThreadDesktopComposited
@ stub -version=0x601+ DwmpDxSetContentHostingInformation
@ stub -version=0x601+ DwmpDxUnbindSwapChain
@ stub -version=0x601+ DwmpDxUpdateWindowRedirectionBltSurface
@ stub -version=0x600+ DwmpDxUpdateWindowSharedSurface
@ stub -version=0x600+ DwmpEnableRedirection
@ stub -version=0x600+ DwmpGetAssessment
@ stub -version=0x600+ DwmpGetAssessmentUsage
@ stub -version=0x601+ DwmpGetColorizationParameters
@ stub -version=0x601+ DwmpGetCompositionTimingInfoEx
@ stub -version=0x600+ DwmpGetGlobalState
@ stub -version=0x600+ DwmpIsCompositionCapable
@ stub -version=0x600+ DwmpIsSessionDWM
@ stub -version=0x600+ DwmpOpenGraphicsStream
@ stub -version=0x601+ DwmpQueryThumbnailType
@ stub -version=0x600+ DwmpRegisterThumbnail
@ stub -version=0x600+ DwmpRestartComposition
@ stub -version=0x600+ DwmpSetAssessmentUsage
@ stub -version=0x601+ DwmpSetColorizationColor
@ stub -version=0x600+ DwmpSetColorizationParameters
@ stub -version=0x600+ DwmpSetGraphicsStreamTransformHint
@ stub -version=0x600+ DwmpStartOrStopFlip3D
@ stub -version=0x600+ DwmpStartupViaUserInit
@ stub -version=0x600+ DwmQueryThumbnailSourceSize
@ stub -version=0x600+ DwmRegisterThumbnail
@ stub -version=0x600+ DwmSetDxFrameDuration
@ stub -version=0x601+ DwmSetIconicLivePreviewBitmap
@ stub -version=0x601+ DwmSetIconicThumbnail
@ stub -version=0x600+ DwmSetPresentParameters
@ stub -version=0x600+ DwmSetWindowAttribute
@ stub -version=0x600+ DwmUnregisterThumbnail
@ stub -version=0x600+ DwmUpdateThumbnailProperties