@ stdcall D3DKMTCreateDCFromMemory(ptr)
@ stdcall D3DKMTDestroyDCFromMemory(ptr)
@ stdcall GetFontFileData(long long int64 ptr long)
@ stdcall GetFontFileInfo(long long ptr long long)
@ stdcall GetFontRealizationInfo(ptr ptr)
@ stdcall BeginGdiRendering()
@ stdcall CreateBitmapFromDxSurface()
@ stdcall CreateBitmapFromDxSurface2()
@ stdcall D3DKMTSetProcessSchedulingPriorityClass(ptr ptr)
@ stdcall EndGdiRendering()
@ stdcall D3DKMTCloseAdapter(ptr)
@ stdcall D3DKMTGetPresentHistory(ptr)
@ stdcall D3DKMTGetPresentQueueEvent(ptr ptr)
@ stdcall D3DKMTOpenAdapterFromGdiDisplayName(ptr)
@ stdcall D3DKMTOpenAdapterFromHdc(ptr)
@ stdcall D3DKMTQueryAdapterInfo(ptr)