@ stdcall -stub DirectInput8Create(long long ptr ptr ptr)
@ stdcall -stub -private DllCanUnloadNow()
@ stdcall -stub -private DllGetClassObject(ptr ptr ptr)
@ stdcall -stub -private DllRegisterServer()
@ stdcall -stub -private DllUnregisterServer()
