@ stdcall -stub D3DRMColorGetAlpha(long)
@ stdcall -stub D3DRMColorGetBlue(long)
@ stdcall -stub D3DRMColorGetGreen(long)
@ stdcall -stub D3DRMColorGetRed(long)
@ stdcall -stub D3DRMCreateColorRGB(float float float)
@ stdcall -stub D3DRMCreateColorRGBA(float float float float)
@ stdcall -stub D3DRMMatrixFromQuaternion(ptr ptr)
@ stdcall -stub D3DRMQuaternionFromRotation(ptr ptr float)
@ stdcall -stub D3DRMQuaternionMultiply(ptr ptr ptr)
@ stdcall -stub D3DRMQuaternionSlerp(ptr ptr ptr float)
@ stdcall -stub D3DRMVectorAdd(ptr ptr ptr)
@ stdcall -stub D3DRMVectorCrossProduct(ptr ptr ptr)
@ stdcall -stub D3DRMVectorDotProduct(ptr ptr)
@ stdcall -stub D3DRMVectorModulus(ptr)
@ stdcall -stub D3DRMVectorNormalize(ptr)
@ stdcall -stub D3DRMVectorRandom(ptr)
@ stdcall -stub D3DRMVectorReflect(ptr ptr ptr)
@ stdcall -stub D3DRMVectorRotate(ptr ptr ptr float)
@ stdcall -stub D3DRMVectorScale(ptr ptr float)
@ stdcall -stub D3DRMVectorSubtract(ptr ptr ptr)
@ stdcall -stub Direct3DRMCreate(ptr)
@ stdcall -stub -private DllCanUnloadNow()
@ stdcall -stub -private DllGetClassObject(ptr ptr ptr)
