# winecrt - Wine -> ReactOS crt vista+ Dll
@ stub -arch=i386 __libm_sse2_acos
@ stub -arch=i386 __libm_sse2_acosf
@ stub -arch=i386 __libm_sse2_asin
@ stub -arch=i386 __libm_sse2_asinf
@ stub -arch=i386 __libm_sse2_atan
@ stub -arch=i386 __libm_sse2_atan2
@ stub -arch=i386 __libm_sse2_atanf
@ stub -arch=i386 __libm_sse2_cos
@ stub -arch=i386 __libm_sse2_cosf
@ stub -arch=i386 __libm_sse2_exp
@ stub -arch=i386 __libm_sse2_expf
@ stub -arch=i386 __libm_sse2_log
@ stub -arch=i386 __libm_sse2_log10
@ stub -arch=i386 __libm_sse2_log10f
@ stub -arch=i386 __libm_sse2_logf
@ stub -arch=i386 __libm_sse2_pow
@ stub -arch=i386 __libm_sse2_powf
@ stub -arch=i386 __libm_sse2_sin
@ stub -arch=i386 __libm_sse2_sinf
@ stub -arch=i386 __libm_sse2_tan
@ stub -arch=i386 __libm_sse2_tanf
@ cdecl -stub  wctype(ptr)
@ cdecl -stub  _lock_locales(ptr)
@ cdecl -stub  ___lc_locale_name_func(ptr)
@ cdecl -stub  _unlock_locales()
@ cdecl -stub  _get_stream_buffer_pointers()
@ cdecl -stub  _configure_narrow_argv()
@ cdecl -stub  _configure_wide_argv()
@ cdecl -stub  _crt_atexit()
@ cdecl -stub  _execute_onexit_table()
@ cdecl -stub  _get_initial_narrow_environment()
@ cdecl -stub  _get_initial_wide_environment()
@ cdecl -stub  _initialize_narrow_environment()
@ cdecl -stub  _initialize_onexit_table()
@ cdecl -stub  _initialize_wide_environment()
@ cdecl -stub  _invalid_parameter_noinfo()
@ cdecl -stub  _invalid_parameter_noinfo_noreturn()
@ cdecl -stub  _register_onexit_function()
@ cdecl -stub  _register_thread_local_exe_atexit_callback()
@ cdecl -stub  _hypotf(long long)
