;Windows 7 (checked as of 8/17/2021)
@ stdcall -version=0x601+ AccessCheck() ADVAPI32.AccessCheck
@ stdcall -version=0x601+ AccessCheckAndAuditAlarmW() ADVAPI32.AccessCheckAndAuditAlarmW
@ stdcall -version=0x601+ AccessCheckByType() ADVAPI32.AccessCheckByType
@ stdcall -version=0x601+ AccessCheckByTypeAndAuditAlarmW() ADVAPI32.AccessCheckByTypeAndAuditAlarmW
@ stdcall -version=0x601+ AccessCheckByTypeResultList() ADVAPI32.AccessCheckByTypeResultList
@ stdcall -version=0x601+ AccessCheckByTypeResultListAndAuditAlarmByHandleW() ADVAPI32.AccessCheckByTypeResultListAndAuditAlarmByHandleW
@ stdcall -version=0x601+ AccessCheckByTypeResultListAndAuditAlarmW() ADVAPI32.AccessCheckByTypeResultListAndAuditAlarmW 
@ stdcall -version=0x601+ AcquireSRWLockExclusive() ntdll.AcquireSRWLockExclusive
@ stdcall -version=0x601+ AcquireSRWLockShared() ntdll.AcquireSRWLockShared
@ stdcall -version=0x601+ AddAccessAllowedAce() ADVAPI32.AddAccessAllowedAce
@ stdcall -version=0x601+ AddAccessAllowedAceEx() ADVAPI32.AddAccessAllowedAceEx
@ stdcall -version=0x601+ AddAccessAllowedObjectAce() ADVAPI32.AddAccessAllowedObjectAce
@ stdcall -version=0x601+ AddAccessDeniedAce() ADVAPI32.AddAccessDeniedAce
@ stdcall -version=0x601+ AddAccessDeniedAceEx() ADVAPI32.AddAccessDeniedAceEx
@ stdcall -version=0x601+ AddAccessDeniedObjectAce() ADVAPI32.AddAccessDeniedObjectAce
@ stdcall -version=0x601+ AddAce() ADVAPI32.AddAce
@ stdcall -version=0x601+ AddAuditAccessAce() ADVAPI32.AddAuditAccessAce
@ stdcall -version=0x601+ AddAuditAccessAceEx() ADVAPI32.AddAuditAccessAceEx
@ stdcall -version=0x601+ AddAuditAccessObjectAce() ADVAPI32.AddAuditAccessObjectAce
@ stdcall -version=0x601+ AddMandatoryAce() ADVAPI32.AddMandatoryAce
@ stdcall -version=0x601+ AdjustTokenGroups() ADVAPI32.AdjustTokenGroups
@ stdcall -version=0x601+ AdjustTokenPrivileges() ADVAPI32.AdjustTokenPrivileges
@ stdcall -version=0x601+ AllocateAndInitializeSid() ADVAPI32.AllocateAndInitializeSid
@ stdcall -version=0x601+ AllocateLocallyUniqueId() ADVAPI32.AllocateLocallyUniqueId
@ stdcall -version=0x601+ AreAllAccessesGranted() ADVAPI32.AreAllAccessesGranted
@ stdcall -version=0x601+ AreAnyAccessesGranted() ADVAPI32.AreAnyAccessesGranted
@ stdcall -version=0x601+ AreFileApisANSI() kernel32.AreFileApisANSI
@ stub -version=0x601+ BaseDllFreeResourceId
@ stub -version=0x601+ BaseDllMapResourceIdW
@ stub -version=0x601 BaseGetProcessDllPath
@ stub -version=0x601 BaseGetProcessExePath
@ stub -version=0x601 BaseInvalidateDllSearchPathCache
@ stub -version=0x601 BaseInvalidateProcessSearchPathCache
@ stub -version=0x601 BaseReleaseProcessDllPath
@ stub -version=0x601 BaseReleaseProcessExePath
@ stdcall -version=0x601+ Beep() kernel32.Beep
@ stub -version=0x601-0x603 BemCopyReference
@ stub -version=0x601-0x603 BemCreateContractFrom
@ stub -version=0x601-0x603 BemCreateReference
@ stub -version=0x601-0x603 BemFreeContract
@ stub -version=0x601-0x603 BemFreeReference
@ stdcall -version=0x601+ CallbackMayRunLong() kernel32.CallbackMayRunLong
@ stdcall -version=0x601+ CancelIoEx() kernel32.CancelIoEx
@ stdcall -version=0x601+ CancelThreadpoolIo() ntdll.TpCancelAsyncIoOperation
@ stdcall -version=0x601+ CancelWaitableTimer() kernel32.CancelWaitableTimer
@ stdcall -version=0x601+ ChangeTimerQueueTimer() kernel32.ChangeTimerQueueTimer
@ stub -version=0x601+ CheckGroupPolicyEnabled
@ stdcall -version=0x601+ CheckTokenMembership() ADVAPI32.CheckTokenMembership
@ stdcall -version=0x601+ CloseHandle() kernel32.CloseHandle
@ stdcall -version=0x601+ CloseThreadpool() ntdll.TpReleasePool
@ stdcall -version=0x601+ CloseThreadpoolCleanupGroup() ntdll.TpReleaseCleanupGroup
@ stdcall -version=0x601+ CloseThreadpoolCleanupGroupMembers() ntdll.TpReleaseCleanupGroupMembers
@ stdcall -version=0x601+ CloseThreadpoolIo() ntdll.TpReleaseIoCompletion
@ stdcall -version=0x601+ CloseThreadpoolTimer() ntdll.TpReleaseTimer
@ stdcall -version=0x601+ CloseThreadpoolWait() ntdll.TpReleaseWait
@ stdcall -version=0x601+ CloseThreadpoolWork() ntdll.TpReleaseWork
@ stdcall -version=0x601+ CompareFileTime() kernel32.CompareFileTime
@ stdcall -version=0x601+ CompareStringA() kernel32.CompareStringA
@ stdcall -version=0x601+ CompareStringEx() kernel32.CompareStringEx
@ stdcall -version=0x601+ CompareStringOrdinal() kernel32.CompareStringOrdinal
@ stdcall -version=0x601+ CompareStringW() kernel32.CompareStringW
@ stdcall -version=0x601+ ConnectNamedPipe() kernel32.ConnectNamedPipe
@ stdcall -version=0x601+ ConvertDefaultLocale() kernel32.ConvertDefaultLocale
@ stdcall -version=0x601+ ConvertToAutoInheritPrivateObjectSecurity() ADVAPI32.ConvertToAutoInheritPrivateObjectSecurity
@ stdcall -version=0x601+ CopySid() ADVAPI32.CopySid
@ stdcall -version=0x601+ CreateDirectoryA() kernel32.CreateDirectoryA
@ stdcall -version=0x601+ CreateDirectoryW() kernel32.CreateDirectoryW
@ stdcall -version=0x601+ CreateEventA() kernel32.CreateEventA
@ stdcall -version=0x601+ CreateEventExA() kernel32.CreateEventExA
@ stdcall -version=0x601+ CreateEventExW() kernel32.CreateEventExW
@ stdcall -version=0x601+ CreateEventW() kernel32.CreateEventW
@ stdcall -version=0x601+ CreateFileA() kernel32.CreateFileA
@ stdcall -version=0x601+ CreateFileMappingNumaW() kernel32.CreateFileMappingNumaW
@ stdcall -version=0x601+ CreateFileMappingW() kernel32.CreateFileMappingW
@ stdcall -version=0x601+ CreateFileW() kernel32.CreateFileW
@ stdcall -version=0x601+ CreateIoCompletionPort() kernel32.CreateIoCompletionPort
@ stdcall -version=0x601+ CreateMutexA() kernel32.CreateMutexA
@ stdcall -version=0x601+ CreateMutexExA() kernel32.CreateMutexExA
@ stdcall -version=0x601+ CreateMutexExW() kernel32.CreateMutexExW
@ stdcall -version=0x601+ CreateMutexW() kernel32.CreateMutexW
@ stdcall -version=0x601+ CreateNamedPipeW() kernel32.CreateNamedPipeW
@ stdcall -version=0x601+ CreatePipe() kernel32.CreatePipe
@ stdcall -version=0x601+ CreatePrivateObjectSecurity() kernel32.CreatePrivateObjectSecurity
@ stdcall -version=0x601+ CreatePrivateObjectSecurityEx() kernel32.CreatePrivateObjectSecurityEx
@ stdcall -version=0x601+ CreatePrivateObjectSecurityWithMultipleInheritance()
@ stdcall -version=0x601+ CreateRemoteThread() kernel32.CreateRemoteThread
@ stdcall -version=0x601+ CreateRemoteThreadEx() kernel32.CreateRemoteThreadEx
@ stdcall -version=0x601+ CreateRestrictedToken() kernel32.CreateRestrictedToken
@ stdcall -version=0x601+ CreateSemaphoreExW() kernel32.CreateSemaphoreExW
@ stdcall -version=0x601+ CreateThread() kernel32.CreateThread
@ stdcall -version=0x601+ CreateThreadpool() kernel32.CreateThreadpool
@ stdcall -version=0x601+ CreateThreadpoolCleanupGroup() kernel32.CreateThreadpoolCleanupGroup
@ stdcall -version=0x601+ CreateThreadpoolIo() kernel32.CreateThreadpoolIo
@ stdcall -version=0x601+ CreateThreadpoolTimer() kernel32.CreateThreadpoolTimer
@ stdcall -version=0x601+ CreateThreadpoolWait() kernel32.CreateThreadpoolWait
@ stdcall -version=0x601+ CreateThreadpoolWork() kernel32.CreateThreadpoolWork
@ stdcall -version=0x601+ CreateTimerQueue() kernel32.CreateTimerQueue
@ stdcall -version=0x601+ CreateTimerQueueTimer() kernel32.CreateTimerQueueTimer
@ stdcall -version=0x601+ CreateWaitableTimerExW() kernel32.CreateWaitableTimerExW
@ stdcall -version=0x601+ CreateWellKnownSid() ADVAPI32.CreateWellKnownSid
@ stdcall -version=0x601+ DebugBreak() kernel32.DebugBreak
@ stdcall -version=0x601+ DecodePointer() ntdll.RtlDecodePointer;
@ stdcall -version=0x601+ DecodeSystemPointer() ntdll.RtlDecodeSystemPointer;
@ stdcall -version=0x601+ DefineDosDeviceW() kernel32.DefineDosDeviceW
@ stdcall -version=0x601+ DeleteAce() ADVAPI32.DeleteAce
@ stdcall -version=0x601+ DeleteCriticalSection() ntdll.RtlDeleteCriticalSection;
@ stdcall -version=0x601+ DeleteFileA() kernel32.DeleteFileA
@ stdcall -version=0x601+ DeleteFileW() kernel32.DeleteFileW
@ stdcall -version=0x601+ DeleteProcThreadAttributeList() kernel32.DeleteProcThreadAttributeList
@ stdcall -version=0x601+ DeleteTimerQueueEx() kernel32.DeleteTimerQueueEx
@ stdcall -version=0x601+ DeleteTimerQueueTimer() kernel32.DeleteTimerQueueTimer
@ stdcall -version=0x601+ DeleteVolumeMountPointW() kernel32.DeleteVolumeMountPointW
@ stdcall -version=0x601+ DestroyPrivateObjectSecurity() ADVAPI32.DestroyPrivateObjectSecurity
@ stdcall -version=0x601+ DeviceIoControl() kernel32.DeviceIoControl
@ stdcall -version=0x601+ DisableThreadLibraryCalls() kernel32.DisableThreadLibraryCalls
@ stdcall -version=0x601+ DisassociateCurrentThreadFromCallback() ntdll.TpDisassociateCallback;
@ stdcall -version=0x601+ DisconnectNamedPipe() kernel32.DisconnectNamedPipe
@ stdcall -version=0x601+ DuplicateHandle() kernel32.DuplicateHandle
@ stdcall -version=0x601+ DuplicateToken() ADVAPI32.DuplicateToken
@ stdcall -version=0x601+ DuplicateTokenEx() ADVAPI32.DuplicateTokenEx
@ stdcall -version=0x601+ EncodePointer() ntdll.RtlEncodePointer;
@ stdcall -version=0x601+ EncodeSystemPointer() ntdll.RtlEncodeSystemPointer;
@ stdcall -version=0x601+ EnterCriticalSection() ntdll.RtlEnterCriticalSection;
@ stdcall -version=0x601+ EnumCalendarInfoExEx() kernel32.EnumCalendarInfoExEx
@ stdcall -version=0x601+ EnumCalendarInfoExW() kernel32.EnumCalendarInfoExW
@ stdcall -version=0x601+ EnumCalendarInfoW() kernel32.EnumCalendarInfoW
@ stdcall -version=0x601+ EnumDateFormatsExEx() kernel32.EnumDateFormatsExEx
@ stdcall -version=0x601+ EnumDateFormatsExW() kernel32.EnumDateFormatsExW
@ stdcall -version=0x601+ EnumDateFormatsW() kernel32.EnumDateFormatsW
@ stdcall -version=0x601+ EnumLanguageGroupLocalesW() kernel32.EnumLanguageGroupLocalesW
@ stdcall -version=0x601+ EnumSystemCodePagesW() kernel32.EnumSystemCodePagesW
@ stdcall -version=0x601+ EnumSystemLanguageGroupsW() kernel32.EnumSystemLanguageGroupsW
@ stdcall -version=0x601+ EnumSystemLocalesA() kernel32.EnumSystemLocalesA
@ stdcall -version=0x601+ EnumSystemLocalesEx() kernel32.EnumSystemLocalesEx
@ stdcall -version=0x601+ EnumSystemLocalesW() kernel32.EnumSystemLocalesW
@ stdcall -version=0x601+ EnumTimeFormatsEx() kernel32.EnumTimeFormatsEx
@ stdcall -version=0x601+ EnumTimeFormatsW() kernel32.EnumTimeFormatsW
@ stdcall -version=0x601+ EnumUILanguagesW() kernel32.EnumUILanguagesW
@ stdcall -version=0x601+ EqualDomainSid() ADVAPI32.EqualDomainSid
@ stdcall -version=0x601+ EqualPrefixSid() ADVAPI32.EqualPrefixSid
@ stdcall -version=0x601+ EqualSid() ADVAPI32.EqualSid
@ stdcall -version=0x601+ ExitProcess() ntdll.RtlExitUserProcess ;6.1 and higher (x64) and 6.2 and higher (x86);
@ stdcall -version=0x601+ ExitThread() ntdll.RtlExitUserThread;
@ stdcall -version=0x601+ ExpandEnvironmentStringsA() kernel32.ExpandEnvironmentStringsA
@ stdcall -version=0x601+ ExpandEnvironmentStringsW() kernel32.ExpandEnvironmentStringsW
@ stdcall -version=0x601+ FatalAppExitA() kernel32.FatalAppExitA
@ stdcall -version=0x601+ FatalAppExitW() kernel32.FatalAppExitW
@ stdcall -version=0x601+ FileTimeToLocalFileTime() kernel32.FileTimeToLocalFileTime
@ stdcall -version=0x601+ FileTimeToSystemTime() kernel32.FileTimeToSystemTime
@ stdcall -version=0x601+ FindClose() kernel32.FindClose
@ stdcall -version=0x601+ FindCloseChangeNotification() kernel32.FindCloseChangeNotification
@ stdcall -version=0x601+ FindFirstChangeNotificationA() kernel32.FindFirstChangeNotificationA
@ stdcall -version=0x601+ FindFirstChangeNotificationW() kernel32.FindFirstChangeNotificationW
@ stdcall -version=0x601+ FindFirstFileA() kernel32.FindFirstFileA
@ stdcall -version=0x601+ FindFirstFileExA() kernel32.FindFirstFileExA
@ stdcall -version=0x601+ FindFirstFileExW() kernel32.FindFirstFileExW
@ stdcall -version=0x601+ FindFirstFileW() kernel32.FindFirstFileW
@ stdcall -version=0x601+ FindFirstFreeAce() ADVAPI32.FindFirstFreeAce
@ stdcall -version=0x601+ FindFirstVolumeW() kernel32.FindFirstVolumeW
@ stdcall -version=0x601+ FindNLSString() kernel32.FindNLSString
@ stdcall -version=0x601+ FindNLSStringEx() kernel32.FindNLSStringEx
@ stdcall -version=0x601+ FindNextChangeNotification() kernel32.FindNextChangeNotification
@ stdcall -version=0x601+ FindNextFileA() kernel32.FindNextFileA
@ stdcall -version=0x601+ FindNextFileW() kernel32.FindNextFileW
@ stdcall -version=0x601+ FindNextVolumeW() kernel32.FindNextVolumeW
@ stdcall -version=0x601+ FindResourceExW() kernel32.FindResourceExW
@ stdcall -stub -version=0x601+ FindStringOrdinal() ;kernel32.FindStringOrdinal
@ stdcall -version=0x601+ FindVolumeClose() kernel32.FindVolumeClose
@ stdcall -version=0x601+ FlsAlloc() kernel32.FlsAlloc
@ stdcall -version=0x601+ FlsFree() kernel32.FlsFree
@ stdcall -version=0x601+ FlsGetValue() kernel32.FlsGetValue
@ stdcall -version=0x601+ FlsSetValue() kernel32.FlsSetValue
@ stdcall -version=0x601+ FlushFileBuffers() kernel32.FlushFileBuffers

@ stdcall -version=0x601+ TerminateProcess() kernel32.TerminateProcess
@ stdcall -version=0x601+ TerminateThread() kernel32.TerminateThread
@ stdcall -version=0x601+ TlsAlloc() kernel32.TlsAlloc
@ stdcall -version=0x601+ TlsFree() kernel32.TlsFree
@ stdcall -version=0x601+ TlsGetValue() kernel32.TlsGetValue
@ stdcall -version=0x601+ TlsSetValue() kernel32.TlsSetValue
@ stdcall -version=0x601+ TransactNamedPipe() kernel32.TransactNamedPipe
@ stdcall -version=0x601+ TryAcquireSRWLockExclusive() ntdll.RtlTryAcquireSRWLockExclusive
@ stdcall -version=0x601+ TryAcquireSRWLockShared() ntdll.RtlTryAcquireSRWLockShared
@ stdcall -version=0x601+ TryEnterCriticalSection() ntdll.RtlTryEnterCriticalSection
@ stdcall -version=0x601+ TrySubmitThreadpoolCallback() kernel32.TrySubmitThreadpoolCallback
@ stdcall -version=0x601+ TzSpecificLocalTimeToSystemTime() kernel32.TzSpecificLocalTimeToSystemTime
@ stdcall -version=0x601+ UnlockFile() kernel32.UnlockFile
@ stdcall -version=0x601+ UnlockFileEx() kernel32.UnlockFileEx
@ stdcall -version=0x601+ UnmapViewOfFile() kernel32.UnmapViewOfFile
@ stdcall -version=0x601+ UnregisterWaitEx() kernel32.UnregisterWaitEx
@ stdcall -version=0x601+ UpdateProcThreadAttribute() kernel32.UpdateProcThreadAttribute
@ stdcall -version=0x601+ VerLanguageNameA() kernel32.VerLanguageNameA
@ stdcall -version=0x601+ VerLanguageNameW() kernel32.VerLanguageNameW
@ stdcall -version=0x601+ VirtualAlloc() kernel32.VirtualAlloc
@ stdcall -version=0x601+ VirtualAllocEx() kernel32.VirtualAllocEx
@ stdcall -version=0x601+ VirtualAllocExNuma() kernel32.VirtualAllocExNuma
@ stdcall -version=0x601+ VirtualFree() kernel32.VirtualFree
@ stdcall -version=0x601+ VirtualFreeEx() kernel32.VirtualFreeEx
@ stdcall -version=0x601+ VirtualProtect() kernel32.VirtualProtect
@ stdcall -version=0x601+ VirtualProtectEx() kernel32.VirtualProtectEx
@ stdcall -version=0x601+ VirtualQuery() kernel32.VirtualQuery
@ stdcall -version=0x601+ VirtualQueryEx() kernel32.VirtualQueryEx
@ stdcall -version=0x601+ WaitForMultipleObjectsE() kernel32.WaitForMultipleObjectsEx
@ stdcall -version=0x601+ WaitForSingleObject() kernel32.WaitForSingleObject
@ stdcall -version=0x601+ WaitForSingleObjectEx() kernel32.WaitForSingleObjectEx
@ stdcall -version=0x601+ WaitForThreadpoolIoCallbacks() ntdll.TpWaitForIoCompletion;
@ stdcall -version=0x601+ WaitForThreadpoolTimerCallbacks() ntdll.TpWaitForTimer;
@ stdcall -version=0x601+ WaitForThreadpoolWaitCallbacks() ntdll.TpWaitForWait;
@ stdcall -version=0x601+ WaitForThreadpoolWorkCallbacks() ntdll.TpWaitForWork;
@ stdcall -version=0x601+ WaitNamedPipeW() kernel32.WaitNamedPipeW
@ stdcall -version=0x601+ WideCharToMultiByte() kernel32.WideCharToMultiByte
@ stdcall -version=0x601+ Wow64DisableWow64FsRedirection() kernel32.Wow64DisableWow64FsRedirection
@ stdcall -version=0x601+ Wow64RevertWow64FsRedirection() kernel32.Wow64RevertWow64FsRedirection
@ stdcall -version=0x601+ WriteFile() kernel32.WriteFile
@ stdcall -version=0x601+ WriteFileEx() kernel32.WriteFileEx
@ stdcall -version=0x601+ WriteFileGather()	kernel32.WriteFileGather
@ stdcall -version=0x601+ WriteProcessMemory() kernel32.WriteProcessMemory
@ stdcall -arch=x86_64 -version=0x601+ __C_specific_handler() kernel32.__C_specific_handler
@ stdcall -arch=x86_64 -version=0x601+ __chkstk() kernel32.__chkstk
@ stdcall -arch=x86_64 -version=0x601+ __misaligned_access() kernel32.__misaligned_access
@ stdcall -arch=x86_64 -version=0x601+ _local_unwind() kernel32._local_unwind
@ stdcall -version=0x601+ lstrcmp() kernel32.lstrcmp
@ stdcall -version=0x601+ lstrcmpA() kernel32.lstrcmpA
@ stdcall -version=0x601+ lstrcmpW() kernel32.lstrcmpW 
@ stdcall -version=0x601+ lstrcmpi() kernel32.lstrcmpi 
@ stdcall -version=0x601+ lstrcmpiA() kernel32.lstrcmpiA 
@ stdcall -version=0x601+ lstrcmpiW() kernel32.lstrcmpiW 
@ stdcall -version=0x601+ lstrcpyn() kernel32.lstrcpyn 
@ stdcall -version=0x601+ lstrcpynA() kernel32.lstrcpynA
@ stdcall -version=0x601+ lstrcpynW() kernel32.lstrcpynW 
@ stdcall -version=0x601+ lstrlen() kernel32.lstrlen 
@ stdcall -version=0x601+ lstrlenA() kernel32.lstrlenA 
@ stdcall -version=0x601+ lstrlenW() kernel32.lstrlenW
 
;Windows 8 stuff (Unchecked)
;@ stdcall -version=0x602+ ActivateActCt() kernel32.ActivateActCt
;@ stub -version=0x602+ AddRefActCtx	
;@ stub -version=0x602+ AddResourceAttributeAce	
;@ stub -version=0x602+ AddSIDToBoundaryDescriptor	
;@ stub -version=0x602+ AddScopedPolicyIDAce	
;@ stub -version=0x602+ AdjustTokenDeviceClaims	
;@ stub -version=0x602+ AdjustTokenDeviceGroups	
;@ stub -version=0x602+ AdjustTokenUserClaims	
;@ stub -version=0x602+ AllocConsole	
;@ stub -version=0x602+ AttachConsole	
;@ stub -version=0x602+ BaseCheckAppcompatCache	
;@ stub -version=0x602+ BaseCheckAppcompatCacheEx	
;@ stub -version=0x602+ BaseCleanupAppcompatCacheSupport	
;@ stub -version=0x602+ BaseDumpAppcompatCache	
;@ stub -version=0x602+ BaseFlushAppcompatCache	
;@ stub -version=0x602+ BaseInitAppcompatCacheSupport	
;@ stub -version=0x602+ BaseIsAppcompatInfrastructureDisabled	
;@ stub -version=0x602+ BaseMarkFileForDelete	
;@ stub -version=0x602+ BaseUpdateAppcompatCache	
;@ stub -version=0x602+ BasepAdjustObjectAttributesForPrivateNamespace	
;@ stub -version=0x602+ BasepCopyFileCallback	
;@ stub -version=0x602+ BasepCopyFileExW	
;@ stub -version=0x602+ BasepNotifyTrackingService	
;@ stub -version=0x602+ CLOSE_LOCAL_HANDLE_INTERNAL	
;@ stub -version=0x602+ CallbackDetectedUnrecoverableError	
;@ stub -version=0x602+ CancelIo	
@ stdcall -version=0x602+ CancelSynchronousIo() kernel32.CancelSynchronousIo
@ stub -version=0x602+ CharLowerA	
@ stub -version=0x602+ CharLowerBuffA	
@ stub -version=0x602+ CharLowerBuffW	
@ stub -version=0x602+ CharLowerW	
@ stub -version=0x602+ CharNextA	
@ stub -version=0x602+ CharNextExA	
@ stub -version=0x602+ CharNextW	
@ stub -version=0x602+ CharPrevA	
@ stub -version=0x602+ CharPrevExA	
@ stub -version=0x602+ CharPrevW	
@ stub -version=0x602+ CharUpperA	
@ stub -version=0x602+ CharUpperBuffA	
@ stub -version=0x602+ CharUpperBuffW	
@ stub -version=0x602+ CharUpperW	
@ stub -version=0x602+ CheckTokenCapability	
@ stub -version=0x602+ CheckTokenMembershipEx	
@ stub -version=0x602+ ChrCmpIA	
@ stub -version=0x602+ ChrCmpIW	
@ stub -version=0x602+ ClearCommBreak	
@ stub -version=0x602+ ClearCommError	
@ stub -version=0x602+ ClosePrivateNamespace	
@ stub -version=0x602+ CloseTrace	
@ stub -version=0x602+ ContinueDebugEvent	
@ stub -version=0x602+ ControlTraceA	
@ stub -version=0x602+ ControlTraceW	
@ stub -version=0x602+ CopyFileExW	
@ stub -version=0x602+ CreateActCtxW	
@ stub -version=0x602+ CreateBoundaryDescriptorW	
@ stub -version=0x602+ CreateConsoleScreenBuffer	
@ stub -version=0x602+ CreateDirectoryExW	
@ stub -version=0x602+ CreateFile2	
@ stub -version=0x602+ CreateHardLinkW	
@ stub -version=0x602+ CreateMemoryResourceNotification	
@ stub -version=0x602+ CreatePrivateNamespaceW	
@ stub -version=0x602+ CreateProcessA	
@ stub -version=0x602+ CreateProcessAsUserW	
@ stub -version=0x602+ CreateProcessInternalA	
@ stub -version=0x602+ CreateProcessInternalW	
@ stub -version=0x602+ CreateProcessW	
@ stub -version=0x602+ CreateSymbolicLinkW	
@ stub -version=0x602+ CtrlRoutine	
@ stub -version=0x602+ DeactivateActCtx	
@ stub -version=0x602+ DebugActiveProcess	
@ stub -version=0x602+ DebugActiveProcessStop	
@ stub -version=0x602+ DelayLoadFailureHook	
@ stub -version=0x602+ DelayLoadFailureHookLookup	
@ stub -version=0x602+ DeleteBoundaryDescriptor	
@ stub -version=0x602+ DeleteSynchronizationBarrier	
@ stub -version=0x602+ DisablePredefinedHandleTableInternal	
@ stub -version=0x602+ DsBindWithSpnExW	
@ stub -version=0x602+ DsCrackNamesW	
@ stub -version=0x602+ DsFreeDomainControllerInfoW	
@ stub -version=0x602+ DsFreeNameResultW	
@ stub -version=0x602+ DsFreePasswordCredentials	
@ stub -version=0x602+ DsGetDomainControllerInfoW	
@ stub -version=0x602+ DsMakePasswordCredentialsW	
@ stub -version=0x602+ DsUnBindW	
@ stub -version=0x602+ EmptyWorkingSet	
@ stub -version=0x602+ EnableTraceEx2	
@ stub -version=0x602+ EnterCriticalPolicySectionInternal	
@ stub -version=0x602+ EnterSynchronizationBarrier	
@ stub -version=0x602+ EnumDeviceDrivers	
@ stub -version=0x602+ EnumDynamicTimeZoneInformation	
@ stub -version=0x602+ EnumPageFilesA	
@ stub -version=0x602+ EnumPageFilesW	
@ stub -version=0x602+ EnumProcessModules	
@ stub -version=0x602+ EnumProcessModulesEx	
@ stub -version=0x602+ EnumProcesses	
@ stub -version=0x602+ EnumResourceLanguagesExA	
@ stub -version=0x602+ EnumResourceLanguagesExW	
@ stub -version=0x602+ EnumResourceNamesExA	
@ stub -version=0x602+ EnumResourceNamesExW	
@ stub -version=0x602+ EnumResourceTypesExA	
@ stub -version=0x602+ EnumResourceTypesExW	
@ stub -version=0x602+ EnumSystemFirmwareTables	
@ stub -version=0x602+ EnumerateTraceGuidsEx	
@ stub -version=0x602+ EnumerateTraces	
@ stub -version=0x602+ EscapeCommFunction	
@ stub -version=0x602+ EventAccessControl	
@ stub -version=0x602+ EventAccessQuery	
@ stub -version=0x602+ EventAccessRemove	
@ stub -version=0x602+ EventActivityIdControl	
@ stub -version=0x602+ EventEnabled	
@ stub -version=0x602+ EventProviderEnabled	
@ stub -version=0x602+ EventRegister	
@ stub -version=0x602+ EventSetInformation	
@ stub -version=0x602+ EventUnregister	
@ stub -version=0x602+ EventWrite	
@ stub -version=0x602+ EventWriteEx	
@ stub -version=0x602+ EventWriteString	
@ stub -version=0x602+ EventWriteTransfer	
@ stub -version=0x602+ FillConsoleOutputAttribute	
@ stub -version=0x602+ FillConsoleOutputCharacterA	
@ stub -version=0x602+ FillConsoleOutputCharacterW	
@ stub -version=0x602+ FindActCtxSectionGuid	
@ stub -version=0x602+ FindActCtxSectionStringW	
@ stub -version=0x602+ FlushConsoleInputBuffer	
@ stub -version=0x602+ FlushInstructionCache	
@ stub -version=0x602+ ForceSyncFgPolicyInternal	
@ stub -version=0x602+ FreeConsole	
@ stub -version=0x602+ FreeGPOListInternalA	
@ stub -version=0x602+ FreeGPOListInternalW	
@ stub -version=0x602+ GenerateConsoleCtrlEvent	
@ stub -version=0x602+ GenerateGPNotificationInternal	
@ stub -version=0x602+ GetAcceptLanguagesA	
@ stub -version=0x602+ GetAcceptLanguagesW	
@ stub -version=0x602+ GetAdjustObjectAttributesForPrivateNamespaceRoutine	
@ stub -version=0x602+ GetAppContainerAce	
@ stub -version=0x602+ GetAppContainerNamedObjectPath	
@ stub -version=0x602+ GetApplicationRecoveryCallback	
@ stub -version=0x602+ GetApplicationRestartSettings	
@ stub -version=0x602+ GetAppliedGPOListInternalA	
@ stub -version=0x602+ GetAppliedGPOListInternalW	
@ stub -version=0x602+ GetCommConfig	
@ stub -version=0x602+ GetCommMask	
@ stub -version=0x602+ GetCommModemStatus	
@ stub -version=0x602+ GetCommProperties	
@ stub -version=0x602+ GetCommState	
@ stub -version=0x602+ GetCommTimeouts	
@ stub -version=0x602+ GetConsoleCP	
@ stub -version=0x602+ GetConsoleCursorInfo	
@ stub -version=0x602+ GetConsoleInputExeNameA	
@ stub -version=0x602+ GetConsoleInputExeNameW	
@ stub -version=0x602+ GetConsoleMode	
@ stub -version=0x602+ GetConsoleOutputCP	
@ stub -version=0x602+ GetConsoleScreenBufferInfo	
@ stub -version=0x602+ GetConsoleScreenBufferInfoEx	
@ stub -version=0x602+ GetConsoleTitleW	
@ stub -version=0x602+ GetCurrentActCtx	
@ stub -version=0x602+ GetCurrentThreadStackLimits	
@ stub -version=0x602+ GetDateFormatA	
@ stub -version=0x602+ GetDateFormatEx	
@ stub -version=0x602+ GetDateFormatW	
@ stub -version=0x602+ GetDeviceDriverBaseNameA	
@ stub -version=0x602+ GetDeviceDriverBaseNameW	
@ stub -version=0x602+ GetDeviceDriverFileNameA	
@ stub -version=0x602+ GetDeviceDriverFileNameW	
@ stub -version=0x602+ GetDynamicTimeZoneInformationEffectiveYears	
@ stub -version=0x602+ GetEightBitStringToUnicodeSizeRoutine	
@ stub -version=0x602+ GetEightBitStringToUnicodeStringRoutine	
@ stub -version=0x602+ GetFileInformationByHandleEx	
@ stub -version=0x602+ GetFileVersionInfoByHandle	
@ stub -version=0x602+ GetFileVersionInfoExA	
@ stub -version=0x602+ GetFileVersionInfoExW	
@ stub -version=0x602+ GetFileVersionInfoSizeExA	
@ stub -version=0x602+ GetFileVersionInfoSizeExW	
@ stub -version=0x602+ GetGPOListInternalA	
@ stub -version=0x602+ GetGPOListInternalW	
@ stub -version=0x602+ GetLargePageMinimum	
@ stub -version=0x602+ GetLargestConsoleWindowSize	
@ stub -version=0x602+ GetMappedFileNameA	
@ stub -version=0x602+ GetMappedFileNameW	
@ stub -version=0x602+ GetModuleBaseNameA	
@ stub -version=0x602+ GetModuleBaseNameW	
@ stub -version=0x602+ GetModuleFileNameExA	
@ stub -version=0x602+ GetModuleFileNameExW	
@ stub -version=0x602+ GetModuleInformation	
@ stub -version=0x602+ GetNativeSystemInfo	
@ stub -version=0x602+ GetNativeSystemPageSize	
@ stub -version=0x602+ GetNextFgPolicyRefreshInfoInternal	
@ stub -version=0x602+ GetNumaHighestNodeNumber	
@ stub -version=0x602+ GetNumaNodeProcessorMaskEx	
@ stub -version=0x602+ GetNumberOfConsoleInputEvents	
@ stub -version=0x602+ GetOsSafeBootMode	
@ stub -version=0x602+ GetOverlappedResultEx	
@ stub -version=0x602+ GetPerformanceInfo	
@ stub -version=0x602+ GetPreviousFgPolicyRefreshInfoInternal	
@ stub -version=0x602+ GetProcAddressForCaller	
@ stub -version=0x602+ GetProcessGroupAffinity	
@ stub -version=0x602+ GetProcessImageFileNameA	
@ stub -version=0x602+ GetProcessImageFileNameW	
@ stub -version=0x602+ GetProcessMemoryInfo	
@ stub -version=0x602+ GetProcessWorkingSetSizeEx	
@ stub -version=0x602+ GetProductInfo	
@ stub -version=0x602+ GetRegistryExtensionFlags	
@ stub -version=0x602+ GetSystemFileCacheSize	
@ stub -version=0x602+ GetSystemFirmwareTable	
@ stub -version=0x602+ GetSystemPageSize	
@ stub -version=0x602+ GetSystemTimePreciseAsFileTime	
@ stub -version=0x602+ GetTempPathW	
@ stub -version=0x602+ GetThreadContext	
@ stub -version=0x602+ GetThreadGroupAffinity	
@ stub -version=0x602+ GetThreadIdealProcessorEx	
@ stub -version=0x602+ GetThreadTimes	
@ stub -version=0x602+ GetTimeFormatA	
@ stub -version=0x602+ GetTimeFormatEx	
@ stub -version=0x602+ GetTimeFormatW	
@ stub -version=0x602+ GetTraceEnableFlags	
@ stub -version=0x602+ GetTraceEnableLevel	
@ stub -version=0x602+ GetTraceLoggerHandle	
@ stub -version=0x602+ GetUnicodeStringToEightBitSizeRoutine	
@ stub -version=0x602+ GetUnicodeStringToEightBitStringRoutine	
@ stub -version=0x602+ GetVolumeNameForVolumeMountPointW	
@ stub -version=0x602+ GetVolumePathNamesForVolumeNameW	
@ stub -version=0x602+ GetWriteWatch	
@ stub -version=0x602+ GetWsChanges	
@ stub -version=0x602+ GetWsChangesEx	
@ stub -version=0x602+ HashData	
@ stub -version=0x602+ IdnToAscii	
@ stub -version=0x602+ IdnToUnicode	
@ stub -version=0x602+ InitOnceBeginInitialize	
@ stub -version=0x602+ InitOnceComplete	
@ stub -version=0x602+ InitOnceExecuteOnce	
@ stub -version=0x602+ InitOnceInitialize	
@ stub -version=0x602+ InitializeConditionVariable	
@ stub -version=0x602+ InitializeProcessForWsWatch	
@ stub -version=0x602+ InitializeSynchronizationBarrier	
@ stub -version=0x602+ InternetTimeFromSystemTimeA	
@ stub -version=0x602+ InternetTimeFromSystemTimeW	
@ stub -version=0x602+ InternetTimeToSystemTimeA	
@ stub -version=0x602+ InternetTimeToSystemTimeW	
@ stub -version=0x602+ IsCharAlphaA	
@ stub -version=0x602+ IsCharAlphaNumericA	
@ stub -version=0x602+ IsCharAlphaNumericW	
@ stub -version=0x602+ IsCharAlphaW	
@ stub -version=0x602+ IsCharBlankW	
@ stub -version=0x602+ IsCharCntrlW	
@ stub -version=0x602+ IsCharDigitW	
@ stub -version=0x602+ IsCharLowerA	
@ stub -version=0x602+ IsCharLowerW	
@ stub -version=0x602+ IsCharPunctW	
@ stub -version=0x602+ IsCharSpaceA	
@ stub -version=0x602+ IsCharSpaceW	
@ stub -version=0x602+ IsCharUpperA	
@ stub -version=0x602+ IsCharUpperW	
@ stub -version=0x602+ IsCharXDigitW	
@ stub -version=0x602+ IsInternetESCEnabled	
@ stub -version=0x602+ IsProcessorFeaturePresent	
@ stub -version=0x602+ IsSyncForegroundPolicyRefresh	
@ stub -version=0x602+ IsThreadAFiber	
@ stub -version=0x602+ IsTimeZoneRedirectionEnabled	
@ stub -version=0x602+ IsValidNLSVersion	
@ stub -version=0x602+ LeaveCriticalPolicySectionInternal	
@ stub -version=0x602+ LoadAppInitDlls	
@ stub -version=0x602+ MapPredefinedHandleInternal	
@ stub -version=0x602+ MoveFileExW	
@ stub -version=0x602+ MoveFileWithProgressTransactedW	
@ stub -version=0x602+ MoveFileWithProgressW	
@ stub -version=0x602+ OpenPrivateNamespaceW	
@ stub -version=0x602+ OpenTraceW	
@ stub -version=0x602+ ParseURLA	
@ stub -version=0x602+ ParseURLW	
@ stub -version=0x602+ PathAddBackslashA	
@ stub -version=0x602+ PathAddBackslashW	
@ stub -version=0x602+ PathAddExtensionA	
@ stub -version=0x602+ PathAddExtensionW	
@ stub -version=0x602+ PathAllocCanonicalize	
@ stub -version=0x602+ PathAllocCombine	
@ stub -version=0x602+ PathAppendA	
@ stub -version=0x602+ PathAppendW	
@ stub -version=0x602+ PathCanonicalizeA	
@ stub -version=0x602+ PathCanonicalizeW	
@ stub -version=0x602+ PathCchAddBackslash	
@ stub -version=0x602+ PathCchAddBackslashEx	
@ stub -version=0x602+ PathCchAddExtension	
@ stub -version=0x602+ PathCchAppend	
@ stub -version=0x602+ PathCchAppendEx	
@ stub -version=0x602+ PathCchCanonicalize	
@ stub -version=0x602+ PathCchCanonicalizeEx	
@ stub -version=0x602+ PathCchCombine	
@ stub -version=0x602+ PathCchCombineEx	
@ stub -version=0x602+ PathCchFindExtension	
@ stub -version=0x602+ PathCchIsRoot	
@ stub -version=0x602+ PathCchRemoveBackslash	
@ stub -version=0x602+ PathCchRemoveBackslashEx	
@ stub -version=0x602+ PathCchRemoveExtension	
@ stub -version=0x602+ PathCchRemoveFileSpec	
@ stub -version=0x602+ PathCchRenameExtension	
@ stub -version=0x602+ PathCchSkipRoot	
@ stub -version=0x602+ PathCchStripPrefix	
@ stub -version=0x602+ PathCchStripToRoot	
@ stub -version=0x602+ PathCombineA	
@ stub -version=0x602+ PathCombineW	
@ stub -version=0x602+ PathCommonPrefixA	
@ stub -version=0x602+ PathCommonPrefixW	
@ stub -version=0x602+ PathCreateFromUrlA	
@ stub -version=0x602+ PathCreateFromUrlAlloc	
@ stub -version=0x602+ PathCreateFromUrlW	
@ stub -version=0x602+ PathFileExistsA	
@ stub -version=0x602+ PathFileExistsW	
@ stub -version=0x602+ PathFindExtensionA	
@ stub -version=0x602+ PathFindExtensionW	
@ stub -version=0x602+ PathFindFileNameA	
@ stub -version=0x602+ PathFindFileNameW	
@ stub -version=0x602+ PathFindNextComponentA	
@ stub -version=0x602+ PathFindNextComponentW	
@ stub -version=0x602+ PathGetCharTypeA	
@ stub -version=0x602+ PathGetCharTypeW	
@ stub -version=0x602+ PathGetDriveNumberA	
@ stub -version=0x602+ PathGetDriveNumberW	
@ stub -version=0x602+ PathIsFileSpecA	
@ stub -version=0x602+ PathIsFileSpecW	
@ stub -version=0x602+ PathIsLFNFileSpecA	
@ stub -version=0x602+ PathIsLFNFileSpecW	
@ stub -version=0x602+ PathIsPrefixA	
@ stub -version=0x602+ PathIsPrefixW	
@ stub -version=0x602+ PathIsRelativeA	
@ stub -version=0x602+ PathIsRelativeW	
@ stub -version=0x602+ PathIsRootA	
@ stub -version=0x602+ PathIsRootW	
@ stub -version=0x602+ PathIsSameRootA	
@ stub -version=0x602+ PathIsSameRootW	
@ stub -version=0x602+ PathIsUNCA	
@ stub -version=0x602+ PathIsUNCEx	
@ stub -version=0x602+ PathIsUNCServerA	
@ stub -version=0x602+ PathIsUNCServerShareA	
@ stub -version=0x602+ PathIsUNCServerShareW	
@ stub -version=0x602+ PathIsUNCServerW	
@ stub -version=0x602+ PathIsUNCW	
@ stub -version=0x602+ PathIsURLA	
@ stub -version=0x602+ PathIsURLW	
@ stub -version=0x602+ PathIsValidCharA	
@ stub -version=0x602+ PathIsValidCharW	
@ stub -version=0x602+ PathMatchSpecA	
@ stub -version=0x602+ PathMatchSpecExA	
@ stub -version=0x602+ PathMatchSpecExW	
@ stub -version=0x602+ PathMatchSpecW	
@ stub -version=0x602+ PathParseIconLocationA	
@ stub -version=0x602+ PathParseIconLocationW	
@ stub -version=0x602+ PathRelativePathToA	
@ stub -version=0x602+ PathRelativePathToW	
@ stub -version=0x602+ PathRemoveBackslashA	
@ stub -version=0x602+ PathRemoveBackslashW	
@ stub -version=0x602+ PathRemoveBlanksA	
@ stub -version=0x602+ PathRemoveBlanksW	
@ stub -version=0x602+ PathRemoveExtensionA	
@ stub -version=0x602+ PathRemoveExtensionW	
@ stub -version=0x602+ PathRemoveFileSpecA	
@ stub -version=0x602+ PathRemoveFileSpecW	
@ stub -version=0x602+ PathRenameExtensionA	
@ stub -version=0x602+ PathRenameExtensionW	
@ stub -version=0x602+ PathSkipRootA	
@ stub -version=0x602+ PathSkipRootW	
@ stub -version=0x602+ PathStripPathA	
@ stub -version=0x602+ PathStripPathW	
@ stub -version=0x602+ PathStripToRootA	
@ stub -version=0x602+ PathStripToRootW	
@ stub -version=0x602+ PathUnExpandEnvStringsA	
@ stub -version=0x602+ PathUnExpandEnvStringsW	
@ stub -version=0x602+ PathUnquoteSpacesA	
@ stub -version=0x602+ PathUnquoteSpacesW	
@ stub -version=0x602+ PeekConsoleInputA	
@ stub -version=0x602+ PeekConsoleInputW	
@ stub -version=0x602+ PoolPerAppKeyStateInternal	
@ stub -version=0x602+ PrivCopyFileExW	
@ stub -version=0x602+ ProcessTrace	
@ stub -version=0x602+ PurgeComm	
@ stub -version=0x602+ QISearch	
@ stub -version=0x602+ QueryActCtxSettingsW	
@ stub -version=0x602+ QueryActCtxW	
@ stub -version=0x602+ QueryAllTracesA	
@ stub -version=0x602+ QueryAllTracesW	
@ stub -version=0x602+ QueryMemoryResourceNotification	
@ stub -version=0x602+ QueryOptionalDelayLoadedAPI	
@ stub -version=0x602+ QueryUnbiasedInterruptTime	
@ stub -version=0x602+ QueryWorkingSet	
@ stub -version=0x602+ QueryWorkingSetEx	
@ stub -version=0x602+ QueueUserWorkItem	
@ stub -version=0x602+ ReadConsoleA	
@ stub -version=0x602+ ReadConsoleInputA	
@ stub -version=0x602+ ReadConsoleInputExA	
@ stub -version=0x602+ ReadConsoleInputExW	
@ stub -version=0x602+ ReadConsoleInputW	
@ stub -version=0x602+ ReadConsoleOutputA	
@ stub -version=0x602+ ReadConsoleOutputAttribute	
@ stub -version=0x602+ ReadConsoleOutputCharacterA	
@ stub -version=0x602+ ReadConsoleOutputCharacterW	
@ stub -version=0x602+ ReadConsoleOutputW	
@ stub -version=0x602+ ReadConsoleW	
@ stub -version=0x602+ RefreshPolicyExInternal	
@ stub -version=0x602+ RefreshPolicyInternal	
@ stub -version=0x602+ RegCloseKey	
@ stub -version=0x602+ RegCopyTreeW	
@ stub -version=0x602+ RegCreateKeyExA	
@ stub -version=0x602+ RegCreateKeyExInternalA	
@ stub -version=0x602+ RegCreateKeyExInternalW	
@ stub -version=0x602+ RegCreateKeyExW	
@ stub -version=0x602+ RegDeleteKeyExA	
@ stub -version=0x602+ RegDeleteKeyExInternalA	
@ stub -version=0x602+ RegDeleteKeyExInternalW	
@ stub -version=0x602+ RegDeleteKeyExW	
@ stub -version=0x602+ RegDeleteTreeA	
@ stub -version=0x602+ RegDeleteTreeW	
@ stub -version=0x602+ RegDeleteValueA	
@ stub -version=0x602+ RegDeleteValueW	
@ stub -version=0x602+ RegDisablePredefinedCacheEx	
@ stub -version=0x602+ RegEnumKeyExA	
@ stub -version=0x602+ RegEnumKeyExW	
@ stub -version=0x602+ RegEnumValueA	
@ stub -version=0x602+ RegEnumValueW	
@ stub -version=0x602+ RegFlushKey	
@ stub -version=0x602+ RegGetKeySecurity	
@ stub -version=0x602+ RegGetValueA	
@ stub -version=0x602+ RegGetValueW	
@ stub -version=0x602+ RegKrnGetAppKeyEventAddressInternal	
@ stub -version=0x602+ RegKrnGetAppKeyLoaded	
@ stub -version=0x602+ RegKrnGetClassesEnumTableAddressInternal	
@ stub -version=0x602+ RegKrnGetHKEY_ClassesRootAddress	
@ stub -version=0x602+ RegKrnGetTermsrvRegistryExtensionFlags	
@ stub -version=0x602+ RegKrnResetAppKeyLoaded	
@ stub -version=0x602+ RegKrnSetDllHasThreadStateGlobal	
@ stub -version=0x602+ RegKrnSetTermsrvRegistryExtensionFlags	
@ stub -version=0x602+ RegLoadAppKeyA	
@ stub -version=0x602+ RegLoadAppKeyW	
@ stub -version=0x602+ RegLoadKeyA	
@ stub -version=0x602+ RegLoadKeyW	
@ stub -version=0x602+ RegLoadMUIStringA	
@ stub -version=0x602+ RegLoadMUIStringW	
@ stub -version=0x602+ RegNotifyChangeKeyValue	
@ stub -version=0x602+ RegOpenCurrentUser	
@ stub -version=0x602+ RegOpenKeyExA	
@ stub -version=0x602+ RegOpenKeyExInternalA	
@ stub -version=0x602+ RegOpenKeyExInternalW	
@ stub -version=0x602+ RegOpenKeyExW	
@ stub -version=0x602+ RegOpenUserClassesRoot	
@ stub -version=0x602+ RegQueryInfoKeyA	
@ stub -version=0x602+ RegQueryInfoKeyW	
@ stub -version=0x602+ RegQueryValueExA	
@ stub -version=0x602+ RegQueryValueExW	
@ stub -version=0x602+ RegRestoreKeyA	
@ stub -version=0x602+ RegRestoreKeyW	
@ stub -version=0x602+ RegSaveKeyExA	
@ stub -version=0x602+ RegSaveKeyExW	
@ stub -version=0x602+ RegSetKeySecurity	
@ stub -version=0x602+ RegSetValueExA	
@ stub -version=0x602+ RegSetValueExW	
@ stub -version=0x602+ RegUnLoadKeyA	
@ stub -version=0x602+ RegUnLoadKeyW	
@ stub -version=0x602+ RegisterGPNotificationInternal	
@ stub -version=0x602+ RegisterTraceGuidsA	
@ stub -version=0x602+ RegisterTraceGuidsW	
@ stub -version=0x602+ ReleaseActCtx	
@ stub -version=0x602+ RemapPredefinedHandleInternal	
@ stub -version=0x602+ RemoveTraceCallback	
@ stub -version=0x602+ ReplaceFileW	
@ stub -version=0x602+ ResetWriteWatch	
@ stub -version=0x602+ ResolveDelayLoadedAPI	
@ stub -version=0x602+ ResolveDelayLoadsFromDll	
@ stub -version=0x602+ RsopLoggingEnabledInternal	
@ stub -version=0x602+ SHExpandEnvironmentStringsA	
@ stub -version=0x602+ SHExpandEnvironmentStringsW	
@ stub -version=0x602+ SHLoadIndirectString	
@ stub -version=0x602+ SHRegCloseUSKey	
@ stub -version=0x602+ SHRegCreateUSKeyA	
@ stub -version=0x602+ SHRegCreateUSKeyW	
@ stub -version=0x602+ SHRegDeleteEmptyUSKeyA	
@ stub -version=0x602+ SHRegDeleteEmptyUSKeyW	
@ stub -version=0x602+ SHRegDeleteUSValueA	
@ stub -version=0x602+ SHRegDeleteUSValueW	
@ stub -version=0x602+ SHRegEnumUSKeyA	
@ stub -version=0x602+ SHRegEnumUSKeyW	
@ stub -version=0x602+ SHRegEnumUSValueA	
@ stub -version=0x602+ SHRegEnumUSValueW	
@ stub -version=0x602+ SHRegGetBoolUSValueA	
@ stub -version=0x602+ SHRegGetBoolUSValueW	
@ stub -version=0x602+ SHRegGetUSValueA	
@ stub -version=0x602+ SHRegGetUSValueW	
@ stub -version=0x602+ SHRegOpenUSKeyA	
@ stub -version=0x602+ SHRegOpenUSKeyW	
@ stub -version=0x602+ SHRegQueryInfoUSKeyA	
@ stub -version=0x602+ SHRegQueryInfoUSKeyW	
@ stub -version=0x602+ SHRegQueryUSValueA	
@ stub -version=0x602+ SHRegQueryUSValueW	
@ stub -version=0x602+ SHRegSetUSValueA	
@ stub -version=0x602+ SHRegSetUSValueW	
@ stub -version=0x602+ SHRegWriteUSValueA	
@ stub -version=0x602+ SHRegWriteUSValueW	
@ stub -version=0x602+ SHTruncateString	
@ stub -version=0x602+ ScrollConsoleScreenBufferA	
@ stub -version=0x602+ ScrollConsoleScreenBufferW	
@ stub -version=0x602+ SetClientTimeZoneInformation	
@ stub -version=0x602+ SetCommBreak	
@ stub -version=0x602+ SetCommConfig	
@ stub -version=0x602+ SetCommMask	
@ stub -version=0x602+ SetCommState	
@ stub -version=0x602+ SetCommTimeouts	
@ stub -version=0x602+ SetComputerNameExW	
@ stub -version=0x602+ SetConsoleActiveScreenBuffer	
@ stub -version=0x602+ SetConsoleCP	
@ stub -version=0x602+ SetConsoleCtrlHandler	
@ stub -version=0x602+ SetConsoleCursorInfo	
@ stub -version=0x602+ SetConsoleCursorPosition	
@ stub -version=0x602+ SetConsoleInputExeNameA	
@ stub -version=0x602+ SetConsoleInputExeNameW	
@ stub -version=0x602+ SetConsoleMode	
@ stub -version=0x602+ SetConsoleOutputCP	
@ stub -version=0x602+ SetConsoleScreenBufferInfoEx	
@ stub -version=0x602+ SetConsoleScreenBufferSize	
@ stub -version=0x602+ SetConsoleTextAttribute	
@ stub -version=0x602+ SetConsoleTitleW	
@ stub -version=0x602+ SetConsoleWindowInfo	
@ stub -version=0x602+ SetDynamicTimeZoneInformation	
@ stub -version=0x602+ SetLastConsoleEventActive	
@ stub -version=0x602+ SetProcessGroupAffinity	
@ stub -version=0x602+ SetProcessPreferredUILanguages	
@ stub -version=0x602+ SetProcessWorkingSetSizeEx	
@ stub -version=0x602+ SetSystemFileCacheSize	
@ stub -version=0x602+ SetSystemTime	
@ stub -version=0x602+ SetThreadContext	
@ stub -version=0x602+ SetThreadGroupAffinity	
@ stub -version=0x602+ SetThreadIdealProcessorEx	
@ stub -version=0x602+ SetThreadPreferredUILanguages	
@ stub -version=0x602+ SetThreadUILanguage	
@ stub -version=0x602+ SetThreadpoolTimerEx	
@ stub -version=0x602+ SetThreadpoolWaitEx	
@ stub -version=0x602+ SetTimeZoneInformation	
@ stub -version=0x602+ SetTraceCallback	
@ stub -version=0x602+ SetUnhandledExceptionFilter	
@ stub -version=0x602+ SetupComm	
@ stub -version=0x602+ SleepConditionVariableCS	
@ stub -version=0x602+ SleepConditionVariableSRW	
@ stub -version=0x602+ StartTraceA	
@ stub -version=0x602+ StartTraceW	
@ stub -version=0x602+ StopTraceW	
@ stub -version=0x602+ StrCSpnA	
@ stub -version=0x602+ StrCSpnIA	
@ stub -version=0x602+ StrCSpnIW	
@ stub -version=0x602+ StrCSpnW	
@ stub -version=0x602+ StrCatBuffA	
@ stub -version=0x602+ StrCatBuffW	
@ stub -version=0x602+ StrCatChainW	
@ stub -version=0x602+ StrChrA	
@ stub -version=0x602+ StrChrA_MB	
@ stub -version=0x602+ StrChrIA	
@ stub -version=0x602+ StrChrIW	
@ stub -version=0x602+ StrChrNIW	
@ stub -version=0x602+ StrChrNW	
@ stub -version=0x602+ StrChrW	
@ stub -version=0x602+ StrCmpCA	
@ stub -version=0x602+ StrCmpCW	
@ stub -version=0x602+ StrCmpICA	
@ stub -version=0x602+ StrCmpICW	
@ stub -version=0x602+ StrCmpIW	
@ stub -version=0x602+ StrCmpLogicalW	
@ stub -version=0x602+ StrCmpNA	
@ stub -version=0x602+ StrCmpNCA	
@ stub -version=0x602+ StrCmpNCW	
@ stub -version=0x602+ StrCmpNIA	
@ stub -version=0x602+ StrCmpNICA	
@ stub -version=0x602+ StrCmpNICW	
@ stub -version=0x602+ StrCmpNIW	
@ stub -version=0x602+ StrCmpNW	
@ stub -version=0x602+ StrCmpW	
@ stub -version=0x602+ StrCpyNW	
@ stub -version=0x602+ StrCpyNXA	
@ stub -version=0x602+ StrCpyNXW	
@ stub -version=0x602+ StrDupA	
@ stub -version=0x602+ StrDupW	
@ stub -version=0x602+ StrIsIntlEqualA	
@ stub -version=0x602+ StrIsIntlEqualW	
@ stub -version=0x602+ StrPBrkA	
@ stub -version=0x602+ StrPBrkW	
@ stub -version=0x602+ StrRChrA	
@ stub -version=0x602+ StrRChrIA	
@ stub -version=0x602+ StrRChrIW	
@ stub -version=0x602+ StrRChrW	
@ stub -version=0x602+ StrRStrIA	
@ stub -version=0x602+ StrRStrIW	
@ stub -version=0x602+ StrSpnA	
@ stub -version=0x602+ StrSpnW	
@ stub -version=0x602+ StrStrA	
@ stub -version=0x602+ StrStrIA	
@ stub -version=0x602+ StrStrIW	
@ stub -version=0x602+ StrStrNIW	
@ stub -version=0x602+ StrStrNW	
@ stub -version=0x602+ StrStrW	
@ stub -version=0x602+ StrToInt64ExA	
@ stub -version=0x602+ StrToInt64ExW	
@ stub -version=0x602+ StrToIntA	
@ stub -version=0x602+ StrToIntExA	
@ stub -version=0x602+ StrToIntExW	
@ stub -version=0x602+ StrToIntW	
@ stub -version=0x602+ StrTrimA	
@ stub -version=0x602+ StrTrimW	
@ stub -version=0x602+ TraceEvent	
@ stub -version=0x602+ TraceMessage	
@ stub -version=0x602+ TraceMessageVa	
@ stub -version=0x602+ TraceQueryInformation	
@ stub -version=0x602+ TraceSetInformation	
@ stub -version=0x602+ TransmitCommChar	
@ stub -version=0x602+ UnhandledExceptionFilter	
@ stub -version=0x602+ UnregisterGPNotificationInternal	
@ stub -version=0x602+ UnregisterTraceGuids	
@ stub -version=0x602+ UrlApplySchemeA	
@ stub -version=0x602+ UrlApplySchemeW	
@ stub -version=0x602+ UrlCanonicalizeA	
@ stub -version=0x602+ UrlCanonicalizeW	
@ stub -version=0x602+ UrlCombineA	
@ stub -version=0x602+ UrlCombineW	
@ stub -version=0x602+ UrlCompareA	
@ stub -version=0x602+ UrlCompareW	
@ stub -version=0x602+ UrlCreateFromPathA	
@ stub -version=0x602+ UrlCreateFromPathW	
@ stub -version=0x602+ UrlEscapeA	
@ stub -version=0x602+ UrlEscapeW	
@ stub -version=0x602+ UrlFixupW	
@ stub -version=0x602+ UrlGetLocationA	
@ stub -version=0x602+ UrlGetLocationW	
@ stub -version=0x602+ UrlGetPartA	
@ stub -version=0x602+ UrlGetPartW	
@ stub -version=0x602+ UrlHashA	
@ stub -version=0x602+ UrlHashW	
@ stub -version=0x602+ UrlIsA	
@ stub -version=0x602+ UrlIsNoHistoryA	
@ stub -version=0x602+ UrlIsNoHistoryW	
@ stub -version=0x602+ UrlIsOpaqueA	
@ stub -version=0x602+ UrlIsOpaqueW	
@ stub -version=0x602+ UrlIsW	
@ stub -version=0x602+ UrlUnescapeA	
@ stub -version=0x602+ UrlUnescapeW	
@ stub -version=0x602+ VerFindFileA	
@ stub -version=0x602+ VerFindFileW	
@ stub -version=0x602+ VerQueryValueA	
@ stub -version=0x602+ VerQueryValueW	
@ stub -version=0x602+ VirtualLock	
@ stub -version=0x602+ VirtualUnlock	
@ stub -version=0x602+ WaitCommEvent	
@ stub -version=0x602+ WaitForDebugEvent	
@ stub -version=0x602+ WaitForMachinePolicyForegroundProcessingInternal	
@ stub -version=0x602+ WaitForUserPolicyForegroundProcessingInternal	
@ stub -version=0x602+ WakeAllConditionVariable	
@ stub -version=0x602+ WakeConditionVariable	
@ stub -version=0x602+ WerRegisterMemoryBlock	
@ stub -version=0x602+ WerUnregisterMemoryBlock	
@ stub -version=0x602+ WerpNotifyLoadStringResource	
@ stub -version=0x602+ WerpNotifyUseStringResource	
@ stub -version=0x602+ WriteConsoleA	
@ stub -version=0x602+ WriteConsoleInputA	
@ stub -version=0x602+ WriteConsoleInputW	
@ stub -version=0x602+ WriteConsoleOutputA	
@ stub -version=0x602+ WriteConsoleOutputAttribute	
@ stub -version=0x602+ WriteConsoleOutputCharacterA	
@ stub -version=0x602+ WriteConsoleOutputCharacterW	
@ stub -version=0x602+ WriteConsoleOutputW	
@ stub -version=0x602+ WriteConsoleW	
@ stub -version=0x602+ ZombifyActCtx	
@ stub -version=0x602+ _AddMUIStringToCache	
@ stub -version=0x602+ _GetMUIStringFromCache	
@ stub -version=0x602+ _OpenMuiStringCache	
@ stub -version=0x602+ __dllonexit3	
@ stub -version=0x602+ __wgetmainargs	
@ stub -version=0x602+ _amsg_exit	
@ stub -version=0x602+ _c_exit	
@ stub -version=0x602+ _cexit	
@ stub -version=0x602+ _exit	
@ stub -version=0x602+ _initterm	
@ stub -version=0x602+ _initterm_e	
@ stub -version=0x602+ _invalid_parameter	
@ stub -version=0x602+ _onexit	
@ stub -version=0x602+ _purecall	
@ stub -version=0x602+ _time64	
@ stub -version=0x602+ atexit	
@ stub -version=0x602+ exit	
@ stub -version=0x602+ hgets	
@ stub -version=0x602+ hwprintf	
@ stub -version=0x602+ time	
@ stub -version=0x602+ wprintf


;Windows 8.1 (checked as of 8/17/2021)
@ stub -version=0x603+ AcquireStateLock	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AllocateUserPhysicalPages	;KERNEL32 in 5.0 and higher
@ stub -version=0x603+ AllocateUserPhysicalPagesNuma	;KERNEL32 in 6.0 and higher
@ stub -version=0x603+ AppContainerDeriveSidFromMoniker	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppContainerFreeMemory	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppContainerLookupDisplayNameMrtReference	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppContainerLookupMoniker	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppContainerRegisterSid ;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppContainerUnregisterSid	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXFreeMemory	;ERNEL32 in 6.2 only
@ stub -version=0x603+ AppXGetApplicationData	; KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXGetDevelopmentMode	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXGetOSMaxVersionTested	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ AppXGetOSMinVersion	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXGetPackageCapabilities	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXGetPackageSid	;KERNEL32 in 6.2 only
@ stub -version=0x603 AppXGetPackageState ;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXLookupDisplayName	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXLookupMoniker	;KERNEL32 in 6.2 only
@ stub -version=0x603+ AppXPostSuccessExtension	 
@ stub -version=0x603+ AppXPreCreationExtension	 
@ stub -version=0x603+ AppXReleaseAppXContext	 
@ stub -version=0x603 AppXSetPackageState
@ stub -version=0x603+ BaseFreeAppCompatDataForProcess	 
@ stub -version=0x603+ BaseReadAppCompatDataForProcess	 
@ stub -version=0x603+ CheckIfStateChangeNotificationExists	 
@ stub -version=0x603+ ClosePackageInfo	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ CloseState	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ CloseStateAtom	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CloseStateChangeNotification	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CloseStateContainer	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CloseStateLock	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CommitStateAtom	;KERNEL32 in 6.2 only
@ stdcall -version=0x603+ CopyContext() kernel32.CopyContext
@ stub -version=0x603+ CreateAppContainerToken	 
@ stub -version=0x603+ CreateStateAtom	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CreateStateChangeNotification	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CreateStateContainer	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CreateStateLock	;KERNEL32 in 6.2 only
@ stub -version=0x603+ CreateStateSubcontainer	;KERNEL32 in 6.2 only
@ stub -version=0x603+ DeleteStateAtomValue	;KERNEL32 in 6.2 only
@ stub -version=0x603+ DeleteStateContainer	;KERNEL32 in 6.2 only
@ stub -version=0x603+ DeleteStateContainerValue	;KERNEL32 in 6.2 only
@ stub -version=0x603+ DiscardVirtualMemory	;KERNEL32 in 10.0 and higher
@ stub -version=0x603+ DnsHostnameToComputerNameExW	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ DuplicateStateContainerHandle	;ERNEL32 in 6.2 only
@ stub -version=0x603+ EnumerateStateAtomValues	; KERNEL32 in 6.2 only
@ stub -version=0x603+ EnumerateStateContainerItems	;KERNEL32 in 6.2 only
@ stub -version=0x603+ FindPackagesByPackageFamily	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ FormatApplicationUserModelId	;KERNEL32 in 6.3 and higher
@ stdcall -version=0x603+ FreeUserPhysicalPages() kernel32.FreeUserPhysicalPages
@ stub -version=0x603+ GetAppModelVersion	 
@ stub -version=0x603+ GetApplicationUserModelId	;KERNEL32 in 6.2 and higher
@ stdcall -version=0x603+ GetCompressedFileSizeA() kernel32.GetCompressedFileSizeA
@ stdcall -version=0x603+ GetCompressedFileSizeW() kernel32.GetCompressedFileSizeW
@ stub -version=0x603+ GetCurrentApplicationUserModelId	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetCurrentPackageApplicationContext	 
@ stub -version=0x603+ GetCurrentPackageApplicationResourcesContext	 
@ stub -version=0x603+ GetCurrentPackageContext	 
@ stub -version=0x603+ GetCurrentPackageFamilyName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetCurrentPackageFullName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetCurrentPackageId	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetCurrentPackageInfo	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetCurrentPackagePath	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetCurrentPackageResourcesContext	 
@ stub -version=0x603+ GetCurrentPackageSecurityContext	 
@ stub -version=0x603+ GetEnabledXStateFeatures	;KERNEL32 in some 6.1 and higher
@ stub -version=0x603+ GetHivePath	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetMemoryErrorHandlingCapabilities	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPackageApplicationContext	 
@ stub -version=0x603+ GetPackageApplicationIds	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ GetPackageApplicationProperty	 
@ stub -version=0x603+ GetPackageApplicationPropertyString	 
@ stub -version=0x603+ GetPackageApplicationResourcesContext	 
@ stub -version=0x603+ GetPackageContext	 
@ stub -version=0x603+ GetPackageFamilyName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPackageFullName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPackageId	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPackageInfo	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPackageInstallTime	 
@ stub -version=0x603+ GetPackageOSMaxVersionTested	 
@ stub -version=0x603+ GetPackagePath	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPackagePathByFullName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPackageProperty	 
@ stub -version=0x603+ GetPackagePropertyString	 
@ stub -version=0x603+ GetPackageResourcesContext	 
@ stub -version=0x603+ GetPackageResourcesProperty	 
@ stub -version=0x603+ GetPackageSecurityContext	 
@ stub -version=0x603+ GetPackageSecurityProperty	 
@ stub -version=0x603+ GetPackagesByPackageFamily	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetPhysicallyInstalledSystemMemory	;KERNEL32 in some 6.0 and higher
@ stub -version=0x603+ GetProcessPriorityBoost	;KERNEL32 in some 4.0 and higher
@ stub -version=0x603+ GetRoamingLastObservedChangeTime	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetSerializedAtomBytes	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetStagedPackageOrigin	 
@ stub -version=0x603+ GetStagedPackagePathByFullName	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ GetStateContainerDepth	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetStateFolder	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetStateRootFolder	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetStateSettingsFolder	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetStateVersion	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetSystemAppDataFolder	;KERNEL32 in 6.2 only
@ stub -version=0x603+ GetSystemAppDataKey	;KERNEL32 in 6.2 and higher
@ stdcall -version=0x603+ GetSystemTimes() kernel32.GetSystemTimes
@ stdcall -version=0x603+ GetThreadIOPendingFlag() kernel32.GetThreadIOPendingFlag
@ stub -version=0x603+ GetThreadInformation	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ GetXStateFeaturesMask	;KERNEL32 in some 6.1 and higher
@ stub -version=0x603+ InitializeContext	;KERNEL32 in some 6.1 and higher
@ stub -version=0x603+ InstallELAMCertificateInfo	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ InvalidateAppModelVersionCache	 
@ stub -version=0x603+ IsProcessCritical	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ LocateXStateFeature	;KERNEL32 in some 6.1 and higher
@ stub -version=0x603+ MapUserPhysicalPages() kernel32.MapUserPhysicalPages
@ stub -version=0x603+ OfferVirtualMemory
@ stub -version=0x603+ OpenFileById	;KERNEL32 in 6.0 and higher
@ stub -version=0x603+ OpenPackageInfoByFullName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ OpenState	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ OpenStateAtom	;KERNEL32 in 6.2 only
@ stub -version=0x603+ OpenStateExplicit	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ OverrideRoamingDataModificationTimesInRange	;KERNEL32 in 6.2 only
@ stub -version=0x603+ PackageFamilyNameFromFullName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ PackageFamilyNameFromId	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ PackageFullNameFromId	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ PackageIdFromFullName	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ PackageNameAndPublisherIdFromFamilyName;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ ParseApplicationUserModelId	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ PsmCreateKey	 
@ stub -version=0x603+ PsmEqualApplication	 
@ stub -version=0x603+ PsmEqualPackage	 
@ stub -version=0x603+ PsmGetApplicationNameFromKey	 
@ stub -version=0x603+ PsmGetKeyFromProcess	 
@ stub -version=0x603+ PsmGetKeyFromToken	 
@ stub -version=0x603+ PsmGetPackageFullNameFromKey	 
@ stub -version=0x603+ PsmIsChildKey	 
@ stub -version=0x603+ PsmIsDynamicKey	 
@ stub -version=0x603+ PsmIsValidKey	 
@ stub -version=0x603+ PublishStateChangeNotification	;KERNEL32 in 6.2 only
@ stub -version=0x603+ QueryStateAtomValueInfo	;KERNEL32 in 6.2 only
@ stub -version=0x603+ QueryStateContainerItemInfo;KERNEL32 in 6.2 only
@ stub -version=0x603+ QuirkGetData	 
@ stub -version=0x603+ QuirkGetData2	 
@ stub -version=0x603+ QuirkIsEnabled	 
@ stub -version=0x603+ QuirkIsEnabled2	 
@ stub -version=0x603+ QuirkIsEnabled3	 
@ stub -version=0x603+ QuirkIsEnabledForPackage	 
@ stub -version=0x603+ QuirkIsEnabledForPackage2	 
@ stub -version=0x603+ QuirkIsEnabledForProcess	 
@ stub -version=0x603+ ReadStateAtomValue	;KERNEL32 in 6.2 only
@ stub -version=0x603+ ReadStateContainerValue	;KERNEL32 in 6.2 only
@ stub -version=0x603+ ReclaimVirtualMemory
@ stub -version=0x603+ RegisterBadMemoryNotification	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ RegisterStateChangeNotification	;KERNEL32 in 6.2 only
@ stub -version=0x603+ RegisterStateLock	;KERNEL32 in 6.2 only
@ stub -version=0x603+ ReleaseStateLock	;KERNEL32 in 6.2 only
@ stub -version=0x603+ ReplaceFileExInternal	 
@ stub -version=0x603+ ResetState	;KERNEL32 in 6.2 only
@ stub -version=0x603+ SetComputerNameEx2W	;KERNEL32 in 6.3 and higher
@ stub -version=0x603+ SetFileIoOverlappedRange	;KERNEL32 in 6.0 and higher
@ stdcall -version=0x603+ SetProcessPriorityBoost() kernel32.SetProcessPriorityBoost
@ stub -version=0x603+ SetRoamingLastObservedChangeTime	 
@ stub -version=0x603+ SetStateVersion	;KERNEL32 in 6.2 only
@ stdcall -version=0x603+ SetSystemTimeAdjustment() kernel32.SetSystemTimeAdjustment
@ stub -version=0x603+ SetThreadInformation	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ SetXStateFeaturesMask	;KERNEL32 in some 6.1 and higher
@ stub -version=0x603+ SubscribeStateChangeNotification	;KERNEL32 in 6.2 only
@ stub -version=0x603+ UnregisterBadMemoryNotification	;KERNEL32 in 6.2 and higher
@ stub -version=0x603+ UnregisterStateChangeNotification	;KERNEL32 in 6.2 only
@ stub -version=0x603+ UnregisterStateLock ;KERNEL32 in 6.2 only
@ stub -version=0x603+ UnsubscribeStateChangeNotification	;KERNEL32 in 6.2 only
@ stub -version=0x603+ WriteStateAtomValue	;KERNEL32 in 6.2 only
@ stub -version=0x603+ WriteStateContainerValue	;KERNEL32 in 6.2 only
